"""集级视频补齐 Supervisor（Episode Video Completion Supervisor）。

协调者（reconciler）：维护覆盖台账、Issue 化失败、经 Repair Router 重新入队，
不接管 _run_job / media_pipeline 调度器。

原 app/video_supervisor.py（4,487 行）按关注点拆分为本包下的多个模块：授权与视频计划
绑定（authority.py）、checkpoint 持久化与心跳（checkpoint.py）、覆盖台账重建与陈旧性
判定（coverage.py）、attempts 预算换算（budget.py）、连续性死锁解除与任务冻结/释放
（job_control.py）、逐镜派发（dispatch.py）、Issue 收集与降级级联（issues_cascade.py）、
分镜语义修复提案（storyboard_repair.py）、候选自动采用（adoption.py）、截止收口
（closeout.py）、参考素材预热（assets.py）、主 tick 循环（run_loop.py）、失败安全终态
与韧性外壳（resilience.py）、看门狗巡检（watchdog.py）、运维预览与恢复入口（ops.py），
外加常量/阶段标签（constants.py）与 Pydantic 数据模型（models.py）。

本文件是唯一的稳定入口：全仓所有 `from app.video_supervisor import X` /
`import app.video_supervisor` / `video_supervisor.X` 使用方式必须不经改动继续可用——
下面按来源模块显式再导出每一个符号（用 `name as name` 的 PEP 484 显式重导出写法，
不使用 `from .x import *`，见 app/FILE_CONVENTIONS.toml 的 star_import 闸门）。
新增补齐逻辑请加进对应关注点的子模块，不要加回本文件。
"""
from __future__ import annotations

from .adoption import (
    Any as Any,
    CoverageLedger as CoverageLedger,
    Evaluation as Evaluation,
    EvidenceArtifact as EvidenceArtifact,
    REPORT_ARTIFACT_TYPE as REPORT_ARTIFACT_TYPE,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _adopt_ready_candidates as _adopt_ready_candidates,
    _adopt_ready_candidates_incrementally as _adopt_ready_candidates_incrementally,
    _has_unadopted_ready_candidate as _has_unadopted_ready_candidate,
    _merge_shot_state as _merge_shot_state,
    _rebuild_coverage_ledger_async as _rebuild_coverage_ledger_async,
    _save_checkpoint_async as _save_checkpoint_async,
    _supervisor_checks_can_use_worker_thread as _supervisor_checks_can_use_worker_thread,
    _write_coverage_report as _write_coverage_report,
    annotations as annotations,
    asyncio as asyncio,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    json as json,
    select_best_video_candidate as select_best_video_candidate,
)
from .assets import (
    ASSET_PREP_HEARTBEAT_INTERVAL_S as ASSET_PREP_HEARTBEAT_INTERVAL_S,
    Any as Any,
    SUPERVISOR_HEARTBEAT_STALE_S as SUPERVISOR_HEARTBEAT_STALE_S,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _REFERENCE_ASSET_PREP_LOCKS as _REFERENCE_ASSET_PREP_LOCKS,
    _asset_prep_heartbeat as _asset_prep_heartbeat,
    _prepare_episode_reference_assets as _prepare_episode_reference_assets,
    _reference_asset_scan as _reference_asset_scan,
    _save_checkpoint_async as _save_checkpoint_async,
    _verify_supervisor_paid_authority as _verify_supervisor_paid_authority,
    annotations as annotations,
    asyncio as asyncio,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    json as json,
)
from .authority import (
    Any as Any,
    GrantValidationError as GrantValidationError,
    VideoCompletionGrant as VideoCompletionGrant,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _ensure_supervisor_video_plan as _ensure_supervisor_video_plan,
    _record_grant_validation_failure as _record_grant_validation_failure,
    _supervisor_checks_can_use_worker_thread as _supervisor_checks_can_use_worker_thread,
    _verify_episode_plan_current_async as _verify_episode_plan_current_async,
    _verify_supervisor_paid_authority as _verify_supervisor_paid_authority,
    _verify_supervisor_paid_authority_async as _verify_supervisor_paid_authority_async,
    annotations as annotations,
    asyncio as asyncio,
    bind_video_grant_generation_plan as bind_video_grant_generation_plan,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    validate_video_grant as validate_video_grant,
)
from .budget import (
    Any as Any,
    COST_PER_SECOND_CNY as COST_PER_SECOND_CNY,
    CoverageLedger as CoverageLedger,
    DEFAULT_VIDEO_BUDGET_CAP_CNY as DEFAULT_VIDEO_BUDGET_CAP_CNY,
    FIRST_PASS_BUDGET_FRACTION as FIRST_PASS_BUDGET_FRACTION,
    MAX_ATTEMPTS_PER_SHOT as MAX_ATTEMPTS_PER_SHOT,
    MIN_ATTEMPTS_PER_SHOT as MIN_ATTEMPTS_PER_SHOT,
    SHOT_BUDGET_MULTIPLIER as SHOT_BUDGET_MULTIPLIER,
    ShotCoverageEntry as ShotCoverageEntry,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _budget_view as _budget_view,
    _has_dispatch_budget_capacity as _has_dispatch_budget_capacity,
    _merge_shot_state as _merge_shot_state,
    _rebuild_budgeted_coverage_ledger as _rebuild_budgeted_coverage_ledger,
    _rebuild_budgeted_coverage_ledger_async as _rebuild_budgeted_coverage_ledger_async,
    _rebuild_coverage_ledger_async as _rebuild_coverage_ledger_async,
    _supervisor_checks_can_use_worker_thread as _supervisor_checks_can_use_worker_thread,
    annotations as annotations,
    asyncio as asyncio,
    attempts_for as attempts_for,
    get_conn as get_conn,
    rebuild_coverage_ledger as rebuild_coverage_ledger,
)
from .checkpoint import (
    Any as Any,
    CHECKPOINT_ARTIFACT_TYPE as CHECKPOINT_ARTIFACT_TYPE,
    Evaluation as Evaluation,
    EvidenceArtifact as EvidenceArtifact,
    SUPERVISOR_HEARTBEAT_STALE_S as SUPERVISOR_HEARTBEAT_STALE_S,
    TERMINAL_SUPERVISOR_PHASES as TERMINAL_SUPERVISOR_PHASES,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _CHECKPOINT_WRITE_SEMAPHORE as _CHECKPOINT_WRITE_SEMAPHORE,
    _persist_checkpoint_transaction as _persist_checkpoint_transaction,
    _refresh_supervisor_heartbeat as _refresh_supervisor_heartbeat,
    _run_checkpoint_write as _run_checkpoint_write,
    _save_checkpoint_async as _save_checkpoint_async,
    _supervisor_checks_can_use_worker_thread as _supervisor_checks_can_use_worker_thread,
    annotations as annotations,
    asyncio as asyncio,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    json as json,
    load_latest_checkpoint as load_latest_checkpoint,
    new_id as new_id,
    now as now,
    public_checkpoint_projection as public_checkpoint_projection,
    save_checkpoint as save_checkpoint,
)
from .closeout import (
    Any as Any,
    CoverageLedger as CoverageLedger,
    TERMINAL_SUPERVISOR_PHASES as TERMINAL_SUPERVISOR_PHASES,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _deadline_closeout as _deadline_closeout,
    _deadline_closeout_async as _deadline_closeout_async,
    _finalize_covered as _finalize_covered,
    _finalize_covered_async as _finalize_covered_async,
    _merge_shot_state as _merge_shot_state,
    _release_episode_supervisor as _release_episode_supervisor,
    _run_checkpoint_write as _run_checkpoint_write,
    _stop_supervised_video_jobs as _stop_supervised_video_jobs,
    _write_coverage_report as _write_coverage_report,
    annotations as annotations,
    consume_grant as consume_grant,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    json as json,
    now as now,
    rebuild_coverage_ledger as rebuild_coverage_ledger,
    save_checkpoint as save_checkpoint,
    select_best_video_candidate as select_best_video_candidate,
)
from .constants import (
    ASSET_PREP_HEARTBEAT_INTERVAL_S as ASSET_PREP_HEARTBEAT_INTERVAL_S,
    CHECKPOINT_ARTIFACT_TYPE as CHECKPOINT_ARTIFACT_TYPE,
    CONTROL_PLANE_MAX_RECOVERIES as CONTROL_PLANE_MAX_RECOVERIES,
    COST_PER_SECOND_CNY as COST_PER_SECOND_CNY,
    DISPATCH_HEARTBEAT_INTERVAL_S as DISPATCH_HEARTBEAT_INTERVAL_S,
    FIRST_PASS_BUDGET_FRACTION as FIRST_PASS_BUDGET_FRACTION,
    LIFECYCLE_HEARTBEAT_INTERVAL_S as LIFECYCLE_HEARTBEAT_INTERVAL_S,
    Literal as Literal,
    MAX_ATTEMPTS_PER_SHOT as MAX_ATTEMPTS_PER_SHOT,
    MAX_REPAIR_EPOCHS as MAX_REPAIR_EPOCHS,
    MIN_ATTEMPTS_PER_SHOT as MIN_ATTEMPTS_PER_SHOT,
    REPORT_ARTIFACT_TYPE as REPORT_ARTIFACT_TYPE,
    SHOT_BUDGET_MULTIPLIER as SHOT_BUDGET_MULTIPLIER,
    SUPERVISOR_HEARTBEAT_STALE_S as SUPERVISOR_HEARTBEAT_STALE_S,
    SUPERVISOR_TICK_INTERVAL_S as SUPERVISOR_TICK_INTERVAL_S,
    SUPERVISOR_TICK_MAX_INTERVAL_S as SUPERVISOR_TICK_MAX_INTERVAL_S,
    SupervisorPhase as SupervisorPhase,
    TERMINAL_SUPERVISOR_PHASES as TERMINAL_SUPERVISOR_PHASES,
    VIDEO_COMPLETION_BUSINESS_STAGES as VIDEO_COMPLETION_BUSINESS_STAGES,
    _CHECKPOINT_WRITE_SEMAPHORE as _CHECKPOINT_WRITE_SEMAPHORE,
    _PHASE_LABELS as _PHASE_LABELS,
    _REFERENCE_ASSET_PREP_LOCKS as _REFERENCE_ASSET_PREP_LOCKS,
    annotations as annotations,
    asyncio as asyncio,
    phase_label as phase_label,
)
from .coverage import (
    ACTIVE_JOB_STATUSES as ACTIVE_JOB_STATUSES,
    Any as Any,
    CoverageLedger as CoverageLedger,
    MIN_ATTEMPTS_PER_SHOT as MIN_ATTEMPTS_PER_SHOT,
    Shot as Shot,
    ShotCoverageEntry as ShotCoverageEntry,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _adopted_video_is_usable as _adopted_video_is_usable,
    _compute_chains as _compute_chains,
    _human_adopted as _human_adopted,
    _video_stale_for_shot as _video_stale_for_shot,
    annotations as annotations,
    classify_video_hard_failures as classify_video_hard_failures,
    get_conn as get_conn,
    grade_shot_video as grade_shot_video,
    issues_from_job_failure as issues_from_job_failure,
    json as json,
    load_persisted_shot_issues as load_persisted_shot_issues,
    math as math,
    rebuild_coverage_ledger as rebuild_coverage_ledger,
    video_candidate_selection_score as video_candidate_selection_score,
)
from .dispatch import (
    ACTIVE_JOB_STATUSES as ACTIVE_JOB_STATUSES,
    Any as Any,
    DISPATCH_HEARTBEAT_INTERVAL_S as DISPATCH_HEARTBEAT_INTERVAL_S,
    GrantValidationError as GrantValidationError,
    SUPERVISOR_HEARTBEAT_STALE_S as SUPERVISOR_HEARTBEAT_STALE_S,
    Shot as Shot,
    ShotCoverageEntry as ShotCoverageEntry,
    TERMINAL_SUPERVISOR_PHASES as TERMINAL_SUPERVISOR_PHASES,
    VideoRepairPlan as VideoRepairPlan,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _after_shot_id as _after_shot_id,
    _budget_paused_job_id as _budget_paused_job_id,
    _dispatch as _dispatch,
    _dispatch_heartbeat as _dispatch_heartbeat,
    _dispatch_with_heartbeat as _dispatch_with_heartbeat,
    _dispatch_with_heartbeat_async as _dispatch_with_heartbeat_async,
    _patch_version_supervisor_meta as _patch_version_supervisor_meta,
    _refresh_supervisor_heartbeat as _refresh_supervisor_heartbeat,
    _requeue_no_charge_job as _requeue_no_charge_job,
    _supervisor_checks_can_use_worker_thread as _supervisor_checks_can_use_worker_thread,
    _verify_supervisor_paid_authority as _verify_supervisor_paid_authority,
    annotations as annotations,
    asyncio as asyncio,
    bump_fingerprint_count as bump_fingerprint_count,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    issues_from_enqueue_error as issues_from_enqueue_error,
    json as json,
    load_latest_checkpoint as load_latest_checkpoint,
    now as now,
    persist_shot_issue as persist_shot_issue,
)
from .issues_cascade import (
    CoverageLedger as CoverageLedger,
    Issue as Issue,
    MAX_CHAIN_CASCADE_DEPTH as MAX_CHAIN_CASCADE_DEPTH,
    ShotCoverageEntry as ShotCoverageEntry,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _adopt_fallback as _adopt_fallback,
    _apply_cascade as _apply_cascade,
    _collect_issues as _collect_issues,
    annotations as annotations,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    issues_from_job_failure as issues_from_job_failure,
    issues_from_qa as issues_from_qa,
    json as json,
    load_persisted_shot_issues as load_persisted_shot_issues,
    select_best_video_candidate as select_best_video_candidate,
    should_cascade as should_cascade,
    state_drift_significant as state_drift_significant,
)
from .job_control import (
    Any as Any,
    Issue as Issue,
    IssueSeverity as IssueSeverity,
    _reconcile_terminal_continuity_blocks as _reconcile_terminal_continuity_blocks,
    _release_episode_supervisor as _release_episode_supervisor,
    _stop_supervised_video_jobs as _stop_supervised_video_jobs,
    annotations as annotations,
    get_conn as get_conn,
    json as json,
    now as now,
    persist_shot_issue as persist_shot_issue,
)
from .models import (
    Any as Any,
    BaseModel as BaseModel,
    CoverageLedger as CoverageLedger,
    Field as Field,
    Literal as Literal,
    MIN_ATTEMPTS_PER_SHOT as MIN_ATTEMPTS_PER_SHOT,
    Path as Path,
    RepairLevel as RepairLevel,
    SUPERVISOR_TICK_INTERVAL_S as SUPERVISOR_TICK_INTERVAL_S,
    Shot as Shot,
    ShotCoverageEntry as ShotCoverageEntry,
    StoryboardRepairAffectedAuthority as StoryboardRepairAffectedAuthority,
    StoryboardRepairProposal as StoryboardRepairProposal,
    SupervisorPhase as SupervisorPhase,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _adopted_video_is_usable as _adopted_video_is_usable,
    annotations as annotations,
    json as json,
)
from .ops import (
    Any as Any,
    GrantValidationError as GrantValidationError,
    TERMINAL_SUPERVISOR_PHASES as TERMINAL_SUPERVISOR_PHASES,
    _record_grant_validation_failure as _record_grant_validation_failure,
    _verify_supervisor_paid_authority as _verify_supervisor_paid_authority,
    annotations as annotations,
    asyncio as asyncio,
    get_conn as get_conn,
    get_video_grant as get_video_grant,
    json as json,
    load_latest_checkpoint as load_latest_checkpoint,
    now as now,
    preview_video_completion_repair as preview_video_completion_repair,
    recover_video_completion_runs as recover_video_completion_runs,
    run_video_completion_resilient as run_video_completion_resilient,
    save_checkpoint as save_checkpoint,
)
from .resilience import (
    Any as Any,
    CONTROL_PLANE_MAX_RECOVERIES as CONTROL_PLANE_MAX_RECOVERIES,
    LIFECYCLE_HEARTBEAT_INTERVAL_S as LIFECYCLE_HEARTBEAT_INTERVAL_S,
    SUPERVISOR_HEARTBEAT_STALE_S as SUPERVISOR_HEARTBEAT_STALE_S,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _deadline_closeout_async as _deadline_closeout_async,
    _mark_failed_closed as _mark_failed_closed,
    _mark_failed_closed_async as _mark_failed_closed_async,
    _refresh_supervisor_heartbeat as _refresh_supervisor_heartbeat,
    _release_episode_supervisor as _release_episode_supervisor,
    _run_checkpoint_write as _run_checkpoint_write,
    _run_video_completion_resilient_loop as _run_video_completion_resilient_loop,
    _save_checkpoint_async as _save_checkpoint_async,
    _stop_supervised_video_jobs as _stop_supervised_video_jobs,
    _supervisor_lifecycle_heartbeat_worker as _supervisor_lifecycle_heartbeat_worker,
    annotations as annotations,
    asyncio as asyncio,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    load_latest_checkpoint as load_latest_checkpoint,
    now as now,
    run_video_completion_resilient as run_video_completion_resilient,
    run_video_completion_supervisor as run_video_completion_supervisor,
    save_checkpoint as save_checkpoint,
    threading as threading,
)
from .run_loop import (
    DEFAULT_VIDEO_BUDGET_CAP_CNY as DEFAULT_VIDEO_BUDGET_CAP_CNY,
    FIRST_PASS_BUDGET_FRACTION as FIRST_PASS_BUDGET_FRACTION,
    GrantValidationError as GrantValidationError,
    MAX_REPAIR_EPOCHS as MAX_REPAIR_EPOCHS,
    SHOT_BUDGET_MULTIPLIER as SHOT_BUDGET_MULTIPLIER,
    SUPERVISOR_TICK_INTERVAL_S as SUPERVISOR_TICK_INTERVAL_S,
    SUPERVISOR_TICK_MAX_INTERVAL_S as SUPERVISOR_TICK_MAX_INTERVAL_S,
    TERMINAL_SUPERVISOR_PHASES as TERMINAL_SUPERVISOR_PHASES,
    VideoCompletionGrant as VideoCompletionGrant,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _adopt_fallback as _adopt_fallback,
    _adopt_ready_candidates as _adopt_ready_candidates,
    _adopt_ready_candidates_incrementally as _adopt_ready_candidates_incrementally,
    _amend_storyboard as _amend_storyboard,
    _apply_cascade as _apply_cascade,
    _budget_paused_job_id as _budget_paused_job_id,
    _budget_view as _budget_view,
    _collect_issues as _collect_issues,
    _deadline_closeout_async as _deadline_closeout_async,
    _dispatch_with_heartbeat_async as _dispatch_with_heartbeat_async,
    _ensure_supervisor_video_plan as _ensure_supervisor_video_plan,
    _finalize_covered_async as _finalize_covered_async,
    _has_dispatch_budget_capacity as _has_dispatch_budget_capacity,
    _merge_shot_state as _merge_shot_state,
    _prepare_episode_reference_assets as _prepare_episode_reference_assets,
    _rebuild_budgeted_coverage_ledger_async as _rebuild_budgeted_coverage_ledger_async,
    _rebuild_coverage_ledger_async as _rebuild_coverage_ledger_async,
    _reconcile_terminal_continuity_blocks as _reconcile_terminal_continuity_blocks,
    _record_grant_validation_failure as _record_grant_validation_failure,
    _requeue_no_charge_job as _requeue_no_charge_job,
    _save_checkpoint_async as _save_checkpoint_async,
    _supervisor_checks_can_use_worker_thread as _supervisor_checks_can_use_worker_thread,
    _try_auto_crop as _try_auto_crop,
    _verify_supervisor_paid_authority_async as _verify_supervisor_paid_authority_async,
    annotations as annotations,
    asyncio as asyncio,
    bump_fingerprint_count as bump_fingerprint_count,
    consume_control as consume_control,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    is_fatal as is_fatal,
    load_latest_checkpoint as load_latest_checkpoint,
    now as now,
    route_video_repair as route_video_repair,
    run_video_completion_supervisor as run_video_completion_supervisor,
    validate_video_grant as validate_video_grant,
)
from .storyboard_repair import (
    EvidenceArtifact as EvidenceArtifact,
    GrantValidationError as GrantValidationError,
    Shot as Shot,
    ShotCoverageEntry as ShotCoverageEntry,
    Storyboard as Storyboard,
    StoryboardRepairAffectedAuthority as StoryboardRepairAffectedAuthority,
    StoryboardRepairProposal as StoryboardRepairProposal,
    VideoCompletionGrant as VideoCompletionGrant,
    VideoRepairPlan as VideoRepairPlan,
    VideoSupervisorCheckpoint as VideoSupervisorCheckpoint,
    _amend_storyboard as _amend_storyboard,
    _candidate_storyboard_from_repair as _candidate_storyboard_from_repair,
    _repair_authority_ids as _repair_authority_ids,
    _semantic_storyboard_repair_proposal as _semantic_storyboard_repair_proposal,
    _try_auto_crop as _try_auto_crop,
    _validate_storyboard_repair_proposal as _validate_storyboard_repair_proposal,
    _verify_supervisor_paid_authority as _verify_supervisor_paid_authority,
    annotations as annotations,
    evidence_repository as evidence_repository,
    get_conn as get_conn,
    json as json,
)
from .watchdog import (
    GrantValidationError as GrantValidationError,
    SUPERVISOR_HEARTBEAT_STALE_S as SUPERVISOR_HEARTBEAT_STALE_S,
    TERMINAL_SUPERVISOR_PHASES as TERMINAL_SUPERVISOR_PHASES,
    _deadline_closeout as _deadline_closeout,
    _mark_failed_closed as _mark_failed_closed,
    _record_grant_validation_failure as _record_grant_validation_failure,
    _verify_supervisor_paid_authority as _verify_supervisor_paid_authority,
    annotations as annotations,
    asyncio as asyncio,
    get_conn as get_conn,
    load_latest_checkpoint as load_latest_checkpoint,
    now as now,
    reconcile_stale_video_supervisors as reconcile_stale_video_supervisors,
    save_checkpoint as save_checkpoint,
    video_supervisor_watchdog_loop as video_supervisor_watchdog_loop,
)
