"""Capability Registry：视频 / 参考图领域命令声明。

从 ``app/capabilities/catalog.py`` 的 ``_register_commands``（原 1028 代码行单
函数）按领域拆出，与 ``app/capabilities/handlers/`` 已有的按领域分文件结构对齐。
本文件只声明 ``CommandSpec`` 列表，不做注册——``catalog.py`` 的
``_register_commands`` 统一调用每个领域模块的 ``commands()`` 再逐条
``registry.register_command()``。
"""
from __future__ import annotations

from app.capabilities import inputs as I
from app.capabilities.commands import build_command as _cmd
from app.capabilities.handlers import video as h_video
from app.capabilities.registry import CommandSpec
from app.capabilities.schemas import ConfirmationPolicy, IdempotencyPolicy, RiskLevel


def commands() -> list[CommandSpec]:
    return [
        _cmd(
            "video.generate_episode",
            title="全片生成视频",
            description="批量生成整集待办镜头视频",
            input_model=I.VideoGenerateEpisodeInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_batch",
            handler=h_video.generate_episode,
            rest_routes=(
                "POST /api/episodes/{episode_id}/generate",
                "POST /api/episodes/{episode_id}/video-generation-plan/{plan_id}/execute",
            ),
            tags=("video",),
        ),
        _cmd(
            "video.complete_episode",
            title="补齐全片视频",
            description="集级 Supervisor：持续生成与修复，直到每个分镜都有可用视频",
            input_model=I.VideoCompleteEpisodeInput,
            risk=RiskLevel.R2_MATERIAL,
            # 人工门取消（决策③，docs/TRANSFORM_FREEZE_PLAN.md）：这是内容质量
            # 确认门（"确认分镜后再解锁付费视频"的下一步），不是清库/删数据类
            # 破坏性操作，命令总线两阶段审批对它自动放行。破坏性操作
            # （project.delete / video.clear_* / delivery.review）保持不变。
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_completion_run",
            handler=h_video.complete_episode,
            rest_routes=("POST /api/episodes/{episode_id}/video-completion",),
            tags=("video", "supervisor"),
        ),
        _cmd(
            "video.complete_project",
            title="跨集补齐视频",
            description="项目级全局预算编排：按集顺序启动补齐 Supervisor",
            input_model=I.VideoCompleteProjectInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_project_video_completion",
            handler=h_video.complete_project,
            rest_routes=("POST /api/projects/{project_id}/video-completion",),
            tags=("video", "supervisor"),
        ),
        _cmd(
            "video.generate_shot",
            title="生成单镜视频",
            description="单镜生成，支持 prompt 覆盖、按质检问题修复、原词重抽",
            input_model=I.VideoGenerateShotInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_job",
            handler=h_video.generate_shot,
            rest_routes=("POST /api/shots/{shot_id}/generate",),
            tags=("video",),
        ),
        _cmd(
            "video.stop_shot",
            title="停止单镜视频",
            description="停止单镜活动任务；provider 侧可能仍继续",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="cancels_video_jobs",
            handler=h_video.stop_shot,
            rest_routes=("POST /api/shots/{shot_id}/video/stop",),
            tags=("video",),
        ),
        _cmd(
            "video.stop_episode",
            title="暂停整集视频任务",
            description="可恢复地暂停整集全部活动视频任务",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="pauses_episode_video_jobs",
            handler=h_video.stop_episode,
            rest_routes=("POST /api/episodes/{episode_id}/video/stop",),
            tags=("video",),
        ),
        _cmd(
            "video.adopt_version",
            title="采用视频版本",
            description="人工决策采用某版本，必须记录理由",
            input_model=I.VideoAdoptVersionInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="adopts_version_human_decision",
            handler=h_video.adopt_version,
            rest_routes=("POST /api/shots/{shot_id}/adopt",),
            tags=("video", "gate"),
        ),
        _cmd(
            "video.cancel_adoption",
            title="取消采纳视频",
            description="保留真实模型视频候选，只取消本镜采纳关系；成片禁止使用图片或静音片段代替",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="clears_shot_adoption_and_invalidates_final",
            handler=h_video.cancel_adoption,
            rest_routes=("POST /api/shots/{shot_id}/adoption/cancel",),
            tags=("video", "gate"),
        ),
        _cmd(
            "video.clear_episode",
            title="清空整集媒体",
            description="清空本集媒体产物与模型分析",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_episode_media",
            handler=h_video.clear_episode,
            rest_routes=("POST /api/episodes/{episode_id}/clear-artifacts",),
            tags=("video",),
        ),
        _cmd(
            "video.clear_shot",
            title="清空单镜媒体",
            description="清空单镜媒体产物与模型分析",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_shot_media",
            handler=h_video.clear_shot,
            rest_routes=("POST /api/shots/{shot_id}/clear-artifacts",),
            tags=("video",),
        ),
        _cmd(
            "video.clear_episode_videos",
            title="清空整集视频",
            description="只清空本集视频，保留各镜参考图",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_episode_videos",
            handler=h_video.clear_episode_videos,
            rest_routes=("POST /api/episodes/{episode_id}/videos/clear",),
            tags=("video",),
        ),
        _cmd(
            "video.clear_shot_references",
            title="清空单镜参考图",
            description="只清空本镜参考图，保留视频",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_shot_reference_images",
            handler=h_video.clear_shot_references,
            rest_routes=("POST /api/shots/{shot_id}/references/clear",),
            tags=("video", "reference"),
        ),
        _cmd(
            "video.clear_shot_videos",
            title="清空单镜视频",
            description="只清空本镜视频，保留参考图",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_shot_videos",
            handler=h_video.clear_shot_videos,
            rest_routes=("POST /api/shots/{shot_id}/videos/clear",),
            tags=("video",),
        ),
        _cmd(
            "video.delete_version",
            title="删除视频版本",
            description="删除视频版本；已采用版本禁止直接删",
            input_model=I.VersionScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_version",
            handler=h_video.delete_version,
            rest_routes=("DELETE /api/versions/{version_id}",),
            tags=("video",),
        ),
        _cmd(
            "video.resume_episode",
            title="恢复集视频任务",
            description="重试预算/外部暂停的视频任务",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="resumes_video_jobs",
            handler=h_video.resume_episode,
            rest_routes=("POST /api/episodes/{episode_id}/resume",),
            tags=("video",),
        ),
        _cmd(
            "video.repair_stale_assets",
            title="修复陈旧镜头资产",
            description="依据当前人物与场景视角版本，为陈旧镜头提交新视频版本",
            input_model=I.VideoRepairStaleAssetsInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_jobs_for_stale_shots",
            handler=h_video.repair_stale_assets,
            rest_routes=("POST /api/episodes/{episode_id}/repair-stale-assets",),
            tags=("video", "stale-assets"),
        ),
        _cmd(
            "reference.review",
            title="参考图废弃/恢复",
            description="废弃或恢复参考图；QA 淘汰恢复需理由",
            input_model=I.ReferenceReviewInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="mutates_reference_override",
            handler=h_video.reference_review,
            rest_routes=(
                "DELETE /api/versions/{version_id}/reference-images/{ref_id}",
                "POST /api/versions/{version_id}/reference-images/{ref_id}/restore",
            ),
            tags=("reference",),
        ),
    ]
