"""PRD §5 能力目录：Resource / Domain Tool / UI / Human-only 全量登记。

M2+M3：每个 CommandSpec 挂载真实领域 Handler（见 ``app.capabilities.handlers``），
Handler 只调用现有 ``app.api`` / ``app.planning`` / ``app.orchestration.*`` /
``app.delivery`` / ``app.worker`` / ``app.system_api`` 函数，
禁止用 httpx 反向回调本机 REST。
"""
from __future__ import annotations

from app.capabilities import inputs as I
from app.capabilities.handlers import bible as h_bible
from app.capabilities.handlers import delivery as h_delivery
from app.capabilities.handlers import episode as h_episode
from app.capabilities.handlers import project as h_project
from app.capabilities.handlers import run as h_run
from app.capabilities.handlers import scene as h_scene
from app.capabilities.handlers import screenplay as h_screenplay
from app.capabilities.handlers import storyboard as h_storyboard
from app.capabilities.handlers import system as h_system
from app.capabilities.handlers import video as h_video
from app.capabilities.registry import (
    CommandSpec,
    Handler,
    HumanOnlySpec,
    ResourceSpec,
    UiIntentSpec,
    get_registry,
)
from app.capabilities.schemas import ConfirmationPolicy, IdempotencyPolicy, RiskLevel

_REGISTERED = False


def ensure_registered() -> None:
    global _REGISTERED
    if _REGISTERED:
        _bind_handlers(get_registry())
        return
    registry = get_registry()
    _register_resources(registry)
    _register_ui(registry)
    _register_human_only(registry)
    _register_commands(registry)
    _register_exemptions(registry)
    _bind_handlers(registry)
    _REGISTERED = True


def _bind_handlers(registry) -> None:
    """仅补挂仍缺 handler / preflight 的命令；不覆盖 catalog 已声明的实现。

    ``domain.HANDLER_MAP`` 已掏空，仅作测试补丁兼容；生产 handler 一律在 ``_register_commands`` 声明。
    """
    from dataclasses import replace

    from app.capabilities.handlers.domain import HANDLER_MAP
    from app.capabilities.preflight import PREFLIGHT_MAP

    for name, handler in HANDLER_MAP.items():
        spec = registry.commands.get(name)
        if spec is None or spec.handler is not None:
            continue
        registry.commands[name] = replace(spec, handler=handler)

    for name, preflight_fn in PREFLIGHT_MAP.items():
        spec = registry.commands.get(name)
        if spec is None or spec.preflight is not None:
            continue
        registry.commands[name] = replace(spec, preflight=preflight_fn)

def _cmd(
    name: str,
    *,
    title: str,
    description: str,
    input_model: type,
    risk: RiskLevel,
    confirmation: ConfirmationPolicy,
    idempotency: IdempotencyPolicy,
    scopes: set[str],
    side_effect: str,
    handler: Handler | None = None,
    rest_routes: tuple[str, ...] = (),
    supports_dry_run: bool = True,
    supports_cancel: bool = False,
    mcp_exposed: bool = True,
    admin_only: bool = False,
    tags: tuple[str, ...] = (),
) -> CommandSpec:
    return CommandSpec(
        name=name,
        version="1.0.0",
        title=title,
        description=description,
        input_model=input_model,
        risk=risk,
        confirmation=confirmation,
        idempotency=idempotency,
        scopes=frozenset(scopes),
        side_effect=side_effect,
        supports_dry_run=supports_dry_run,
        supports_cancel=supports_cancel,
        mcp_exposed=mcp_exposed,
        admin_only=admin_only,
        handler=handler,
        rest_routes=rest_routes,
        tags=tags,
    )


def _register_resources(registry) -> None:
    specs = [
        ResourceSpec("projects", "manju://projects", "项目列表", "列出本地项目", rest_routes=("GET /api/projects",)),
        ResourceSpec(
            "project",
            "manju://projects/{project_id}",
            "项目快照",
            "单个项目状态与摘要",
            rest_routes=("GET /api/projects/{project_id}",),
        ),
        ResourceSpec(
            "chapter",
            "manju://projects/{project_id}/chapters/{idx}",
            "章节正文",
            "按章节读取原著（分页/单章，不整本塞入上下文）",
            rest_routes=("GET /api/projects/{project_id}/chapters/{idx}",),
        ),
        ResourceSpec(
            "bible",
            "manju://projects/{project_id}/bible",
            "人物谱",
            "项目人物谱与定妆状态（当前嵌在项目快照中，M1 可拆专用 Resource 读取器）",
        ),
        ResourceSpec(
            "character_portraits",
            "manju://projects/{project_id}/characters/{name}/portraits",
            "角色定妆历史",
            "角色定妆候选与历史版本",
        ),
        ResourceSpec(
            "scenes",
            "manju://projects/{project_id}/scenes",
            "场景库",
            "场景圣经与场景图状态",
        ),
        ResourceSpec(
            "episodes",
            "manju://projects/{project_id}/episodes",
            "分集列表",
            "项目剧集与制作进度（当前嵌在项目快照中）",
        ),
        ResourceSpec(
            "episode",
            "manju://episodes/{episode_id}",
            "剧集快照",
            "单集状态、剧本与分镜摘要",
            rest_routes=("GET /api/episodes/{episode_id}",),
        ),
        ResourceSpec(
            "screenplay",
            "manju://episodes/{episode_id}/screenplay",
            "剧本",
            "单集剧本文本与版本",
        ),
        ResourceSpec(
            "storyboard",
            "manju://episodes/{episode_id}/storyboard",
            "分镜",
            "单集分镜镜头列表",
        ),
        ResourceSpec(
            "shot",
            "manju://shots/{shot_id}",
            "镜头",
            "单镜字段、版本与媒体状态",
        ),
        ResourceSpec(
            "run",
            "manju://runs/{run_id}",
            "Workflow Run",
            "Run 状态、步骤与关联产物",
            rest_routes=("GET /api/runs/{run_id}",),
        ),
        ResourceSpec(
            "run_events",
            "manju://runs/{run_id}/events",
            "Run 事件流",
            "Run 事件列表（可分页）",
            rest_routes=("GET /api/runs/{run_id}/events",),
        ),
        ResourceSpec(
            "artifact",
            "manju://artifacts/{artifact_id}",
            "Artifact",
            "产物内容与可信等级",
            rest_routes=("GET /api/artifacts/{artifact_id}",),
        ),
        ResourceSpec(
            "artifact_lineage",
            "manju://artifacts/{artifact_id}/lineage",
            "Artifact 血缘",
            "产物上下游血缘",
            rest_routes=("GET /api/artifacts/{artifact_id}/lineage",),
        ),
        ResourceSpec(
            "delivery",
            "manju://episodes/{episode_id}/delivery",
            "交付状态",
            "拼接、readiness 与交付包",
            rest_routes=(
                "GET /api/episodes/{episode_id}/delivery/readiness",
                "GET /api/episodes/{episode_id}/delivery/packages",
                "GET /api/episodes/{episode_id}/mix-status",
            ),
        ),
        ResourceSpec(
            "system_health",
            "manju://system/health",
            "系统健康",
            "Jobs/Calls/Health 脱敏视图",
            rest_routes=(
                "GET /api/system/health",
                "GET /api/system/jobs",
                "GET /api/system/calls",
            ),
        ),
        ResourceSpec(
            "gates",
            "manju://gates",
            "人工门禁",
            "待审批 Gate 列表",
            rest_routes=("GET /api/gates",),
        ),
    ]
    for spec in specs:
        registry.register_resource(spec)


def _register_ui(registry) -> None:
    for spec in [
        UiIntentSpec("ui.navigate", "页面导航", "跳转到白名单工作台视图", "navigate", tags=("ui",)),
        UiIntentSpec("ui.select_shot", "选中镜头", "在分镜/评审墙选中指定镜头", "select_shot", tags=("ui",)),
        UiIntentSpec("ui.select_version", "选中版本", "打开指定视频版本比较/预览", "select_version", tags=("ui",)),
        UiIntentSpec("ui.open_evidence", "打开证据", "打开 Artifact / lineage 证据抽屉", "open_evidence", tags=("ui",)),
        UiIntentSpec("ui.open_delivery", "打开交付页", "定位成片台指定 Tab", "open_delivery", tags=("ui",)),
        UiIntentSpec("ui.open_download", "打开下载", "构造本站 allowlist 下载路径，由用户端完成", "open_download", tags=("ui",)),
        UiIntentSpec("ui.preview", "预览媒体", "打开只读预览（图片/视频）", "preview", tags=("ui",)),
        UiIntentSpec(
            "ui.request_directory_grant",
            "请求目录授权",
            "引导用户亲自选择/授权导出目录",
            "request_directory_grant",
            tags=("ui", "human"),
        ),
        UiIntentSpec(
            "ui.open_credentials",
            "打开密钥表单",
            "导航到模型凭证专用表单，不把密钥交给模型",
            "open_credentials",
            tags=("ui", "human"),
        ),
    ]:
        registry.register_ui(spec)


def _register_human_only(registry) -> None:
    for spec in [
        HumanOnlySpec(
            "human.select_upload_file",
            "选择上传小说文件",
            "用户在系统文件选择器中挑选 TXT；前端换发短时效 attachment_token",
            reason="禁止把任意 file_path 暴露给 Agent",
            rest_routes=("POST /api/attachments/novel",),
            tags=("human", "project"),
        ),
        HumanOnlySpec(
            "human.provide_api_key",
            "填写模型 API Key",
            "用户在专用 password input 提交密钥",
            reason="API Key 永不进入模型上下文、对话状态或可见日志",
            related_ui_intent="ui.open_credentials",
            rest_routes=("PUT /api/keys", "PUT /api/models/{model_id}/credentials"),
            tags=("human", "secret"),
        ),
        HumanOnlySpec(
            "human.grant_export_directory",
            "授权导出目录",
            "用户亲自选择本机导出目录",
            reason="Agent 不得浏览任意文件系统",
            related_ui_intent="ui.request_directory_grant",
            tags=("human", "filesystem"),
        ),
    ]:
        registry.register_human_only(spec)


def _register_commands(registry) -> None:
    commands = [
        # —— 项目 ——
        _cmd(
            "project.import_novel",
            title="导入小说",
            description="消费 attachment_token 创建项目并导入 TXT",
            input_model=I.ProjectImportNovelInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="creates_project",
            handler=h_project.import_novel,
            rest_routes=("POST /api/projects",),
            tags=("project",),
        ),
        _cmd(
            "project.delete",
            title="删除项目",
            description="取消后台任务并删除项目及产物",
            input_model=I.ProjectDeleteInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_project",
            handler=h_project.delete_project,
            rest_routes=("DELETE /api/projects/{project_id}",),
            tags=("project",),
        ),
        # —— 人物谱 / 定妆 ——
        _cmd(
            "bible.generate",
            title="生成人物谱",
            description="生成人物谱与定妆照，创建长 Run；feedback 可选，用于「打回重写」时携带修订要求",
            input_model=I.BibleGenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text", "manju:generation-media"},
            side_effect="creates_run_and_may_invalidate_downstream",
            handler=h_bible.generate,
            rest_routes=("POST /api/projects/{project_id}/bible",),
            supports_cancel=True,
            tags=("bible",),
        ),
        _cmd(
            "bible.cancel",
            title="停止人物谱生成",
            description="取消进行中的人物谱任务",
            input_model=I.ProjectScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-text"},
            side_effect="cancels_run",
            handler=h_bible.cancel,
            rest_routes=("POST /api/projects/{project_id}/bible/cancel",),
            tags=("bible",),
        ),
        _cmd(
            "bible.update",
            title="修订人物谱",
            description="保存人物谱修订；若使下游失效需确认",
            input_model=I.BibleUpdateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_bible_may_invalidate_downstream",
            handler=h_bible.update,
            rest_routes=("PUT /api/projects/{project_id}/bible",),
            tags=("bible",),
        ),
        _cmd(
            "portrait.update_prompt",
            title="修改定妆描述",
            description="更新单角色画像 Prompt（可逆编辑）",
            input_model=I.PortraitUpdatePromptInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.OPTIONAL,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_portrait_prompt",
            handler=h_bible.portrait_update_prompt,
            rest_routes=("PUT /api/projects/{project_id}/characters/{character_name}/portrait",),
            tags=("portrait",),
        ),
        _cmd(
            "portrait.generate",
            title="生成定妆照",
            description="生成全部或单角色定妆图（付费图片）",
            input_model=I.PortraitGenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_image_jobs",
            handler=h_bible.portrait_generate,
            rest_routes=("POST /api/projects/{project_id}/refs",),
            supports_cancel=True,
            tags=("portrait",),
        ),
        _cmd(
            "portrait.cancel",
            title="停止定妆生成",
            description="取消定妆图任务",
            input_model=I.ProjectScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="cancels_image_jobs",
            handler=h_bible.portrait_cancel,
            rest_routes=("POST /api/projects/{project_id}/refs/cancel",),
            tags=("portrait",),
        ),
        # —— 场景 ——
        _cmd(
            "scene.generate_bible",
            title="生成场景圣经",
            description="生成场景圣经并启动场景图",
            input_model=I.ProjectScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text", "manju:generation-media"},
            side_effect="creates_run",
            handler=h_scene.generate_bible,
            rest_routes=("POST /api/projects/{project_id}/scene-bible",),
            tags=("scene",),
        ),
        _cmd(
            "scene.generate_refs",
            title="生成场景图",
            description="补齐或重生成场景参考图",
            input_model=I.SceneGenerateRefsInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_image_jobs",
            handler=h_scene.generate_refs,
            rest_routes=("POST /api/projects/{project_id}/scene-refs",),
            supports_cancel=True,
            tags=("scene",),
        ),
        _cmd(
            "scene.cancel_refs",
            title="停止场景图",
            description="取消场景图生成",
            input_model=I.ProjectScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="cancels_image_jobs",
            handler=h_scene.cancel_refs,
            rest_routes=("POST /api/projects/{project_id}/scene-refs/cancel",),
            tags=("scene",),
        ),
        _cmd(
            "scene.update_prompt",
            title="修改场景描述",
            description="更新场景 Prompt；重出图需另行确认",
            input_model=I.SceneUpdatePromptInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.OPTIONAL,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_scene_prompt",
            handler=h_scene.update_prompt,
            rest_routes=("PUT /api/projects/{project_id}/scenes/{scene_name}/prompt",),
            tags=("scene",),
        ),
        # —— 分集 / 剧本 / 分镜 ——
        _cmd(
            "episode.plan",
            title="分集规划",
            description="创建或替换项目分集；replace_existing 会清空剧集链",
            input_model=I.EpisodePlanInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="creates_or_replaces_episodes",
            handler=h_episode.plan,
            rest_routes=("POST /api/projects/{project_id}/plan",),
            tags=("episode",),
        ),
        _cmd(
            "screenplay.generate",
            title="生成剧本",
            description="生成或重新生成单集剧本",
            input_model=I.ScreenplayGenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="creates_run_may_clear_downstream",
            handler=h_screenplay.generate,
            rest_routes=("POST /api/episodes/{episode_id}/screenplay",),
            supports_cancel=True,
            tags=("screenplay",),
        ),
        _cmd(
            "screenplay.generate_batch",
            title="批量生成剧本",
            description="批量生成项目内待办剧本",
            input_model=I.SelectorInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="creates_batch_runs",
            handler=h_screenplay.generate_batch,
            rest_routes=("POST /api/projects/{project_id}/screenplay-all",),
            supports_cancel=True,
            tags=("screenplay",),
        ),
        _cmd(
            "screenplay.cancel",
            title="取消剧本生成",
            description="取消单集或批量剧本任务",
            input_model=I.ScreenplayCancelInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-text"},
            side_effect="cancels_run",
            handler=h_screenplay.cancel,
            rest_routes=(
                "POST /api/episodes/{episode_id}/screenplay/cancel",
                "POST /api/projects/{project_id}/screenplay-all/cancel",
            ),
            tags=("screenplay",),
        ),
        _cmd(
            "screenplay.update",
            title="保存剧本",
            description="结构化保存剧本；下游失效时需确认",
            input_model=I.ScreenplayUpdateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_screenplay_may_invalidate_downstream",
            handler=h_screenplay.update,
            rest_routes=("PUT /api/episodes/{episode_id}/screenplay",),
            tags=("screenplay",),
        ),
        _cmd(
            "storyboard.generate",
            title="生成分镜",
            description="fresh 重建或 resume 从 checkpoint 续跑",
            input_model=I.StoryboardGenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="creates_run_may_overwrite_storyboard",
            handler=h_storyboard.generate,
            rest_routes=(
                "POST /api/episodes/{episode_id}/storyboard",
                "POST /api/episodes/{episode_id}/storyboard/resume",
            ),
            supports_cancel=True,
            tags=("storyboard",),
        ),
        _cmd(
            "storyboard.generate_batch",
            title="批量生成分镜",
            description="批量启动待办分镜",
            input_model=I.SelectorInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="creates_batch_runs",
            handler=h_storyboard.generate_batch,
            rest_routes=("POST /api/projects/{project_id}/storyboard-all",),
            tags=("storyboard",),
        ),
        _cmd(
            "storyboard.cancel",
            title="取消分镜",
            description="取消分镜生成",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-text"},
            side_effect="cancels_run",
            handler=h_storyboard.cancel,
            rest_routes=("POST /api/episodes/{episode_id}/storyboard/cancel",),
            tags=("storyboard",),
        ),
        _cmd(
            "shot.update",
            title="编辑镜头",
            description="结构化 Patch 更新镜头字段；保存前展示失效媒体数",
            input_model=I.ShotUpdateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_shot_may_invalidate_media",
            handler=h_storyboard.shot_update,
            rest_routes=("PUT /api/shots/{shot_id}",),
            tags=("storyboard", "shot"),
        ),
        _cmd(
            "storyboard.confirm",
            title="确认分镜",
            description="人工门禁：确认分镜并进入付费视频阶段",
            input_model=I.StoryboardConfirmInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="human_gate_unlocks_paid_video",
            handler=h_storyboard.confirm,
            rest_routes=("POST /api/episodes/{episode_id}/confirm",),
            tags=("storyboard", "gate"),
        ),
        # —— 视频 / 参考图 ——
        _cmd(
            "video.generate_episode",
            title="全片生成视频",
            description="批量生成整集待办镜头视频",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_batch",
            handler=h_video.generate_episode,
            rest_routes=("POST /api/episodes/{episode_id}/generate",),
            tags=("video",),
        ),
        _cmd(
            "video.generate_shot",
            title="生成单镜视频",
            description="单镜生成，支持 prompt 覆盖、评语重生、原词重抽",
            input_model=I.VideoGenerateShotInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_job",
            handler=h_video.generate_shot,
            rest_routes=("POST /api/shots/{shot_id}/generate",),
            tags=("video",),
        ),
        _cmd(
            "video.stop_shot",
            title="停止单镜视频",
            description="停止单镜活动任务；provider 侧可能仍继续",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="cancels_video_jobs",
            handler=h_video.stop_shot,
            rest_routes=("POST /api/shots/{shot_id}/video/stop",),
            tags=("video",),
        ),
        _cmd(
            "video.adopt_version",
            title="采用视频版本",
            description="人工决策采用某版本，必须记录理由",
            input_model=I.VideoAdoptVersionInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="adopts_version_human_decision",
            handler=h_video.adopt_version,
            rest_routes=("POST /api/shots/{shot_id}/adopt",),
            tags=("video", "gate"),
        ),
        _cmd(
            "video.clear_episode",
            title="清空整集媒体",
            description="清空本集媒体产物与模型分析",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_episode_media",
            handler=h_video.clear_episode,
            rest_routes=("POST /api/episodes/{episode_id}/clear-artifacts",),
            tags=("video",),
        ),
        _cmd(
            "video.clear_shot",
            title="清空单镜媒体",
            description="清空单镜媒体产物与模型分析",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_shot_media",
            handler=h_video.clear_shot,
            rest_routes=("POST /api/shots/{shot_id}/clear-artifacts",),
            tags=("video",),
        ),
        _cmd(
            "video.delete_version",
            title="删除视频版本",
            description="删除视频版本；已采用版本禁止直接删",
            input_model=I.VersionScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_version",
            handler=h_video.delete_version,
            rest_routes=("DELETE /api/versions/{version_id}",),
            tags=("video",),
        ),
        _cmd(
            "video.resume_episode",
            title="恢复集视频任务",
            description="重试预算/外部暂停的视频任务",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="resumes_video_jobs",
            handler=h_video.resume_episode,
            rest_routes=("POST /api/episodes/{episode_id}/resume",),
            tags=("video",),
        ),
        _cmd(
            "reference.review",
            title="参考图废弃/恢复",
            description="废弃或恢复参考图；QA 淘汰恢复需理由",
            input_model=I.ReferenceReviewInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="mutates_reference_override",
            handler=h_video.reference_review,
            rest_routes=(
                "DELETE /api/versions/{version_id}/reference-images/{ref_id}",
                "POST /api/versions/{version_id}/reference-images/{ref_id}/restore",
            ),
            tags=("reference",),
        ),
        # —— 交付 ——
        _cmd(
            "delivery.concatenate",
            title="拼接成片",
            description="拼接已采用镜头为成片",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:delivery"},
            side_effect="creates_concat_job",
            handler=h_delivery.concatenate,
            rest_routes=("POST /api/episodes/{episode_id}/concatenate",),
            tags=("delivery",),
        ),
        _cmd(
            "delivery.check",
            title="检查交付就绪",
            description="重新计算 Delivery Readiness（只读计算）",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R0_READ,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.NONE,
            scopes={"manju:read", "manju:delivery"},
            side_effect="none_read_compute",
            handler=h_delivery.check,
            rest_routes=(),  # GET readiness 走 Resource；此 Tool 供 Agent 主动触发重算
            mcp_exposed=True,
            tags=("delivery",),
        ),
        _cmd(
            "delivery.create_package",
            title="生成交付候选",
            description="在 readiness 通过后创建待审交付包",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:delivery"},
            side_effect="creates_delivery_package",
            handler=h_delivery.create_package,
            rest_routes=("POST /api/episodes/{episode_id}/delivery/package",),
            tags=("delivery",),
        ),
        _cmd(
            "delivery.review",
            title="审批交付包",
            description="批准 / 带风险批准 / 拒绝；最高业务门禁",
            input_model=I.DeliveryReviewInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:delivery"},
            side_effect="human_delivery_gate",
            handler=h_delivery.review,
            rest_routes=("POST /api/episodes/{episode_id}/delivery/approve",),
            tags=("delivery", "gate"),
        ),
        _cmd(
            "delivery.submit_feedback",
            title="提交客户反馈",
            description="记录客户反馈并可发起修订 Run",
            input_model=I.DeliveryFeedbackInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:delivery"},
            side_effect="creates_revision_run",
            handler=h_delivery.submit_feedback,
            rest_routes=("POST /api/episodes/{episode_id}/customer-feedback",),
            tags=("delivery",),
        ),
        # —— Run / Job ——
        _cmd(
            "run.control",
            title="控制 Workflow Run",
            description="cancel / resume / retry 统一入口",
            input_model=I.RunControlInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="mutates_run_state",
            handler=h_run.control,
            rest_routes=(
                "POST /api/runs/{run_id}/cancel",
                "POST /api/runs/{run_id}/resume",
                "POST /api/runs/{run_id}/retry",
            ),
            tags=("run",),
        ),
        _cmd(
            "job.cancel",
            title="取消媒体 Job",
            description="取消单个媒体任务",
            input_model=I.JobCancelInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="cancels_media_job",
            handler=h_run.job_cancel,
            rest_routes=("POST /api/jobs/{job_id}/cancel",),
            tags=("job",),
        ),
        # —— 系统（默认不对外 MCP） ——
        _cmd(
            "system.update_settings",
            title="更新运行设置",
            description="白名单字段更新；禁止 Agent 自动调高预算/并发",
            input_model=I.SystemUpdateSettingsInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="updates_settings",
            handler=h_system.update_settings,
            rest_routes=("PUT /api/settings",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.model_create",
            title="添加模型",
            description="加入自定义模型元数据（不含密钥明文）",
            input_model=I.SystemModelCreateInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="creates_model_metadata",
            handler=h_system.model_create,
            rest_routes=("POST /api/models",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.model_update",
            title="更新模型",
            description="更新自定义模型元数据",
            input_model=I.SystemModelUpdateInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="updates_model_metadata",
            handler=h_system.model_update,
            rest_routes=("PUT /api/models/{model_id}",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.model_delete",
            title="删除模型",
            description="删除自定义模型",
            input_model=I.SystemModelDeleteInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="deletes_model_metadata",
            handler=h_system.model_delete,
            rest_routes=("DELETE /api/models/{model_id}",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.model_test",
            title="测试模型连接",
            description="测试模型连通性；结果必须脱敏",
            input_model=I.SystemModelTestInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.OPTIONAL,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:admin"},
            side_effect="external_connectivity_probe",
            handler=h_system.model_test,
            rest_routes=("POST /api/models/test", "POST /api/models/{model_id}/test"),
            mcp_exposed=True,
            admin_only=False,
            tags=("system",),
        ),
        _cmd(
            "system.set_engine",
            title="切换 Harness Engine",
            description="按项目启用/关闭 Workflow Engine",
            input_model=I.SystemEngineInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="toggles_engine",
            handler=h_system.set_engine,
            rest_routes=("PUT /api/projects/{project_id}/engine",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.mkdir",
            title="在已授权目录下建子目录",
            description="仅允许在用户已授权的 directory_grant 下创建子目录",
            input_model=I.SystemMkdirInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="creates_directory_under_grant",
            handler=h_system.mkdir,
            rest_routes=("POST /api/system/mkdir",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system", "filesystem"),
        ),
        _cmd(
            "system.run_benchmark",
            title="运行 Benchmark",
            description="运行并记录双轨基准",
            input_model=I.BenchmarkRunInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="creates_benchmark_run",
            handler=h_system.run_benchmark,
            rest_routes=("POST /api/benchmarks",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
    ]
    for spec in commands:
        registry.register_command(spec)


def _register_exemptions(registry) -> None:
    """协议/编排/运维入口本身不是领域命令：登记豁免原因，满足覆盖门禁。"""
    registry.exempt_rest(
        "POST /api/system/mcp-tokens",
        "MCP token 生命周期管理是运维端点；Agent/外部 MCP 客户端不能自我签发或升级授权范围",
    )
    registry.exempt_rest(
        "DELETE /api/system/mcp-tokens/{token_id}",
        "同上：token 撤销只能由本机操作者通过监制房页面执行，不进入 Agent/MCP 能力面",
    )
    registry.exempt_rest(
        "POST /api/agent/conversations",
        "Agent 会话编排入口，不直接改变制作领域状态",
    )
    registry.exempt_rest(
        "POST /api/agent/conversations/{conversation_id}/messages",
        "Agent Turn 编排入口；写操作仍经 Command Bus",
    )
    registry.exempt_rest(
        "POST /api/agent/turns/{turn_id}/cancel",
        "仅取消 Agent Turn；底层 Run 需显式 cancel_run 才走 run.control",
    )
    registry.exempt_rest(
        "POST /api/agent/tool-calls/{tool_call_id}/approve",
        "批准卡协议入口，执行仍走已注册 Domain Tool",
    )
    registry.exempt_rest(
        "POST /api/agent/tool-calls/{tool_call_id}/reject",
        "拒绝卡协议入口，不执行领域命令",
    )
    registry.exempt_rest(
        "POST /mcp",
        "MCP JSON-RPC 传输端点；具体 tools/call 映射到 Capability Registry",
    )
