"""PRD §5 能力目录：Resource / Domain Tool / UI / Human-only 全量登记。

M2+M3：每个 CommandSpec 挂载真实领域 Handler（见 ``app.capabilities.handlers``），
Handler 只调用现有 ``app.api`` / ``app.planning`` / ``app.orchestration.*`` /
``app.delivery`` / ``app.worker`` / ``app.system_api`` 函数，
禁止用 httpx 反向回调本机 REST。
"""
from __future__ import annotations

from app.capabilities import inputs as I
from app.capabilities.handlers import bible as h_bible
from app.capabilities.handlers import delivery as h_delivery
from app.capabilities.handlers import episode as h_episode
from app.capabilities.handlers import project as h_project
from app.capabilities.handlers import run as h_run
from app.capabilities.handlers import scene as h_scene
from app.capabilities.handlers import screenplay as h_screenplay
from app.capabilities.handlers import storyboard as h_storyboard
from app.capabilities.handlers import system as h_system
from app.capabilities.handlers import video as h_video
from app.capabilities.registry import (
    CommandSpec,
    Handler,
    HumanOnlySpec,
    ResourceSpec,
    UiIntentSpec,
    get_registry,
)
from app.capabilities.schemas import ConfirmationPolicy, IdempotencyPolicy, RiskLevel

_REGISTERED = False


def ensure_registered() -> None:
    global _REGISTERED
    if _REGISTERED:
        _bind_handlers(get_registry())
        return
    registry = get_registry()
    _register_resources(registry)
    _register_ui(registry)
    _register_human_only(registry)
    _register_commands(registry)
    _register_exemptions(registry)
    _bind_handlers(registry)
    _REGISTERED = True


def _bind_handlers(registry) -> None:
    """仅补挂仍缺 handler / preflight 的命令；不覆盖 catalog 已声明的实现。

    ``domain.HANDLER_MAP`` 已掏空，仅作测试补丁兼容；生产 handler 一律在 ``_register_commands`` 声明。
    """
    from dataclasses import replace

    from app.capabilities.handlers.domain import HANDLER_MAP
    from app.capabilities.preflight import PREFLIGHT_MAP

    for name, handler in HANDLER_MAP.items():
        spec = registry.commands.get(name)
        if spec is None or spec.handler is not None:
            continue
        registry.commands[name] = replace(spec, handler=handler)

    for name, preflight_fn in PREFLIGHT_MAP.items():
        spec = registry.commands.get(name)
        if spec is None or spec.preflight is not None:
            continue
        registry.commands[name] = replace(spec, preflight=preflight_fn)

def _cmd(
    name: str,
    *,
    title: str,
    description: str,
    input_model: type,
    risk: RiskLevel,
    confirmation: ConfirmationPolicy,
    idempotency: IdempotencyPolicy,
    scopes: set[str],
    side_effect: str,
    handler: Handler | None = None,
    rest_routes: tuple[str, ...] = (),
    supports_dry_run: bool = True,
    supports_cancel: bool = False,
    mcp_exposed: bool = True,
    admin_only: bool = False,
    tags: tuple[str, ...] = (),
) -> CommandSpec:
    return CommandSpec(
        name=name,
        version="1.0.0",
        title=title,
        description=description,
        input_model=input_model,
        risk=risk,
        confirmation=confirmation,
        idempotency=idempotency,
        scopes=frozenset(scopes),
        side_effect=side_effect,
        supports_dry_run=supports_dry_run,
        supports_cancel=supports_cancel,
        mcp_exposed=mcp_exposed,
        admin_only=admin_only,
        handler=handler,
        rest_routes=rest_routes,
        tags=tags,
    )


def _register_resources(registry) -> None:
    specs = [
        ResourceSpec("projects", "manju://projects", "项目列表", "列出本地项目", rest_routes=("GET /api/projects",)),
        ResourceSpec(
            "project",
            "manju://projects/{project_id}",
            "项目快照",
            "单个项目状态与摘要",
            rest_routes=("GET /api/projects/{project_id}",),
        ),
        ResourceSpec(
            "chapter",
            "manju://projects/{project_id}/chapters/{idx}",
            "章节正文",
            "按章节读取原著（分页/单章，不整本塞入上下文）",
            rest_routes=("GET /api/projects/{project_id}/chapters/{idx}",),
        ),
        ResourceSpec(
            "bible",
            "manju://projects/{project_id}/bible",
            "人物谱",
            "项目人物谱与定妆状态（当前嵌在项目快照中，M1 可拆专用 Resource 读取器）",
        ),
        ResourceSpec(
            "character_portraits",
            "manju://projects/{project_id}/characters/{name}/portraits",
            "角色定妆历史",
            "角色定妆候选与历史版本",
        ),
        ResourceSpec(
            "scenes",
            "manju://projects/{project_id}/scenes",
            "场景库",
            "场景圣经与场景图状态",
        ),
        ResourceSpec(
            "episodes",
            "manju://projects/{project_id}/episodes",
            "分集列表",
            "项目剧集与制作进度（当前嵌在项目快照中）",
        ),
        ResourceSpec(
            "episode",
            "manju://episodes/{episode_id}",
            "剧集快照",
            "单集状态、剧本与分镜摘要",
            rest_routes=("GET /api/episodes/{episode_id}",),
        ),
        ResourceSpec(
            "screenplay",
            "manju://episodes/{episode_id}/screenplay",
            "剧本",
            "单集已发布剧本文本与版本",
        ),
        ResourceSpec(
            "screenplay_working",
            "manju://episodes/{episode_id}/screenplay/working",
            "剧本工作文档",
            "Repair 环节的服务端工作文档（working Artifact，由 working_screenplay_artifact_id 指向）；供局部修补，不可作为页面交付，既非页面会话草稿（screenplay_drafts）也非已发布剧本（screenplay_json）",
        ),
        ResourceSpec(
            "storyboard",
            "manju://episodes/{episode_id}/storyboard",
            "分镜",
            "单集已发布分镜镜头列表",
        ),
        ResourceSpec(
            "storyboard_working",
            "manju://episodes/{episode_id}/storyboard/working",
            "分镜工作副本",
            "Supervisor 工作镜头集与进度（不可确认/进视频）",
        ),
        ResourceSpec(
            "run_issues",
            "manju://runs/{run_id}/issues",
            "Run Issue 集",
            "未解决结构化 Issue",
        ),
        ResourceSpec(
            "run_patches",
            "manju://runs/{run_id}/patches",
            "Run Patch 历史",
            "局部修补与 diff 证据",
        ),
        ResourceSpec(
            "artifact_certificate",
            "manju://artifacts/{artifact_id}/certificate",
            "完成凭证",
            "绑定精确 Artifact hash 的 Completion Certificate",
        ),
        ResourceSpec(
            "shot",
            "manju://shots/{shot_id}",
            "镜头",
            "单镜字段、版本与媒体状态",
        ),
        ResourceSpec(
            "run",
            "manju://runs/{run_id}",
            "Workflow Run",
            "Run 状态、步骤与关联产物",
            rest_routes=("GET /api/runs/{run_id}",),
        ),
        ResourceSpec(
            "run_events",
            "manju://runs/{run_id}/events",
            "Run 事件流",
            "Run 事件列表（可分页）",
            rest_routes=("GET /api/runs/{run_id}/events",),
        ),
        ResourceSpec(
            "artifact",
            "manju://artifacts/{artifact_id}",
            "Artifact",
            "产物内容与可信等级",
            rest_routes=("GET /api/artifacts/{artifact_id}",),
        ),
        ResourceSpec(
            "artifact_lineage",
            "manju://artifacts/{artifact_id}/lineage",
            "Artifact 血缘",
            "产物上下游血缘",
            rest_routes=("GET /api/artifacts/{artifact_id}/lineage",),
        ),
        ResourceSpec(
            "delivery",
            "manju://episodes/{episode_id}/delivery",
            "交付状态",
            "拼接、readiness 与交付包",
            rest_routes=(
                "GET /api/episodes/{episode_id}/delivery/readiness",
                "GET /api/episodes/{episode_id}/delivery/packages",
                "GET /api/episodes/{episode_id}/mix-status",
            ),
        ),
        ResourceSpec(
            "system_health",
            "manju://system/health",
            "系统健康",
            "Jobs/Calls/Health 脱敏视图",
            rest_routes=(
                "GET /api/system/health",
                "GET /api/system/jobs",
                "GET /api/system/calls",
            ),
        ),
        ResourceSpec(
            "gates",
            "manju://gates",
            "人工门禁",
            "待审批 Gate 列表",
            rest_routes=("GET /api/gates",),
        ),
    ]
    for spec in specs:
        registry.register_resource(spec)


def _register_ui(registry) -> None:
    for spec in [
        UiIntentSpec("ui.navigate", "页面导航", "跳转到白名单工作台视图", "navigate", tags=("ui",)),
        UiIntentSpec("ui.select_shot", "选中镜头", "在分镜/生成台选中指定镜头", "select_shot", tags=("ui",)),
        UiIntentSpec("ui.select_version", "选中版本", "打开指定视频版本比较/预览", "select_version", tags=("ui",)),
        UiIntentSpec("ui.open_evidence", "打开证据", "打开 Artifact / lineage 证据抽屉", "open_evidence", tags=("ui",)),
        UiIntentSpec("ui.open_delivery", "打开交付页", "定位成片台指定 Tab", "open_delivery", tags=("ui",)),
        UiIntentSpec("ui.open_download", "打开下载", "构造本站 allowlist 下载路径，由用户端完成", "open_download", tags=("ui",)),
        UiIntentSpec("ui.preview", "预览媒体", "打开只读预览（图片/视频）", "preview", tags=("ui",)),
        UiIntentSpec(
            "ui.request_directory_grant",
            "请求目录授权",
            "引导用户亲自选择/授权导出目录",
            "request_directory_grant",
            tags=("ui", "human"),
        ),
        UiIntentSpec(
            "ui.open_credentials",
            "打开密钥表单",
            "导航到模型凭证专用表单，不把密钥交给模型",
            "open_credentials",
            tags=("ui", "human"),
        ),
    ]:
        registry.register_ui(spec)


def _register_human_only(registry) -> None:
    for spec in [
        HumanOnlySpec(
            "human.select_upload_file",
            "选择上传小说文件",
            "用户在系统文件选择器中挑选 TXT 或 EPUB；前端换发短时效 attachment_token",
            reason="禁止把任意 file_path 暴露给 Agent",
            rest_routes=("POST /api/attachments/novel",),
            tags=("human", "project"),
        ),
        HumanOnlySpec(
            "human.provide_api_key",
            "填写模型 API Key",
            "用户在专用 password input 提交密钥",
            reason="API Key 永不进入模型上下文、对话状态或可见日志",
            related_ui_intent="ui.open_credentials",
            rest_routes=("PUT /api/keys", "PUT /api/models/{model_id}/credentials"),
            tags=("human", "secret"),
        ),
        HumanOnlySpec(
            "human.grant_export_directory",
            "授权导出目录",
            "用户亲自选择本机导出目录",
            reason="Agent 不得浏览任意文件系统",
            related_ui_intent="ui.request_directory_grant",
            tags=("human", "filesystem"),
        ),
        HumanOnlySpec(
            "human.review_scene_candidate_hard_gates",
            "人工复核场景候选硬门禁",
            "用户放大查看候选图，逐项确认无人、无水印、无禁止文字和空间匹配",
            reason="这是对视觉硬门禁的责任人签署，Agent 不得代替用户勾选或承担风险",
            rest_routes=(
                "POST /api/projects/{project_id}/scenes/{scene_name}/candidates/{artifact_id}/manual-review",
            ),
            tags=("human", "scene", "qa"),
        ),
        HumanOnlySpec(
            "human.choose_episode_target_duration",
            "选择单集目标时长",
            "用户在首版剧本生成前确认单集节奏预算",
            reason="这是会改变剧作节奏与后续成本的创作取舍，当前仅允许用户在前端显式选择",
            rest_routes=("PUT /api/episodes/{episode_id}/target-duration",),
            tags=("human", "episode", "screenplay"),
        ),
        HumanOnlySpec(
            "human.delete_episode",
            "删除单集",
            "用户在分集规划中确认永久删除一集及其全部下游制作内容",
            reason="单集删除不可撤销，且属于用户对原著改编范围的人工取舍",
            rest_routes=("DELETE /api/episodes/{episode_id}",),
            tags=("human", "episode", "destructive"),
        ),
    ]:
        registry.register_human_only(spec)


def _register_commands(registry) -> None:
    commands = [
        # —— 项目 ——
        _cmd(
            "project.import_novel",
            title="导入小说",
            description="消费 attachment_token 创建项目并导入 TXT 或 EPUB，随后自动分集并生成人物谱与多视角素材库",
            input_model=I.ProjectImportNovelInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="creates_project",
            handler=h_project.import_novel,
            rest_routes=("POST /api/projects", "POST /api/projects/import"),
            tags=("project",),
        ),
        _cmd(
            "project.delete",
            title="删除项目",
            description="取消后台任务并删除项目及产物",
            input_model=I.ProjectDeleteInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_project",
            handler=h_project.delete_project,
            rest_routes=("DELETE /api/projects/{project_id}",),
            tags=("project",),
        ),
        # —— 人物谱 / 定妆 ——
        _cmd(
            "bible.generate",
            title="生成人物谱",
            description="生成人物谱与定妆照，创建长 Run；feedback 可选，用于「打回重写」时携带修订要求",
            input_model=I.BibleGenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text", "manju:generation-media"},
            side_effect="creates_run_and_may_invalidate_downstream",
            handler=h_bible.generate,
            rest_routes=("POST /api/projects/{project_id}/bible",),
            supports_cancel=True,
            tags=("bible",),
        ),
        _cmd(
            "bible.cancel",
            title="停止人物谱生成",
            description="取消进行中的人物谱任务",
            input_model=I.ProjectScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-text"},
            side_effect="cancels_run",
            handler=h_bible.cancel,
            rest_routes=("POST /api/projects/{project_id}/bible/cancel",),
            tags=("bible",),
        ),
        _cmd(
            "bible.update",
            title="修订人物谱",
            description="保存人物谱修订；若使下游失效需确认",
            input_model=I.BibleUpdateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_bible_may_invalidate_downstream",
            handler=h_bible.update,
            rest_routes=("PUT /api/projects/{project_id}/bible",),
            tags=("bible",),
        ),
        _cmd(
            "portrait.update_prompt",
            title="修改定妆描述",
            description="更新单角色画像 Prompt（可逆编辑）",
            input_model=I.PortraitUpdatePromptInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.OPTIONAL,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_portrait_prompt",
            handler=h_bible.portrait_update_prompt,
            rest_routes=("PUT /api/projects/{project_id}/characters/{character_name}/portrait",),
            tags=("portrait",),
        ),
        _cmd(
            "portrait.generate",
            title="生成定妆照",
            description="生成全部或单角色定妆图（付费图片）",
            input_model=I.PortraitGenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_image_jobs",
            handler=h_bible.portrait_generate,
            rest_routes=("POST /api/projects/{project_id}/refs",),
            supports_cancel=True,
            tags=("portrait",),
        ),
        _cmd(
            "portrait.cancel",
            title="停止定妆生成",
            description="取消定妆图任务",
            input_model=I.ProjectScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="cancels_image_jobs",
            handler=h_bible.portrait_cancel,
            rest_routes=("POST /api/projects/{project_id}/refs/cancel",),
            tags=("portrait",),
        ),
        _cmd(
            "portrait.regenerate_view",
            title="重做人物单视角",
            description="生成候选视角，通过单图与整包 QA 后原子替换当前视角",
            input_model=I.PortraitViewRegenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_character_view_and_may_replace_ready_view",
            handler=h_bible.portrait_regenerate_view,
            rest_routes=(
                "POST /api/projects/{project_id}/characters/{character_name}/portraits/{portrait_id}/views/{view_role}/regenerate",
            ),
            tags=("portrait", "multiview"),
        ),
        # —— 场景 ——
        _cmd(
            "scene.generate_bible",
            title="生成场景圣经",
            description="生成场景圣经并启动场景图",
            input_model=I.ProjectScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text", "manju:generation-media"},
            side_effect="creates_run",
            handler=h_scene.generate_bible,
            rest_routes=("POST /api/projects/{project_id}/scene-bible",),
            tags=("scene",),
        ),
        _cmd(
            "scene.generate_refs",
            title="生成场景图",
            description="补齐或重生成场景参考图",
            input_model=I.SceneGenerateRefsInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_image_jobs",
            handler=h_scene.generate_refs,
            rest_routes=("POST /api/projects/{project_id}/scene-refs",),
            supports_cancel=True,
            tags=("scene",),
        ),
        _cmd(
            "scene.cancel_refs",
            title="停止场景图",
            description="取消场景图生成",
            input_model=I.ProjectScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="cancels_image_jobs",
            handler=h_scene.cancel_refs,
            rest_routes=("POST /api/projects/{project_id}/scene-refs/cancel",),
            tags=("scene",),
        ),
        _cmd(
            "scene.update_prompt",
            title="修改场景描述",
            description="更新场景 Prompt；重出图需另行确认",
            input_model=I.SceneUpdatePromptInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.OPTIONAL,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_scene_prompt",
            handler=h_scene.update_prompt,
            rest_routes=("PUT /api/projects/{project_id}/scenes/{scene_name}/prompt",),
            tags=("scene",),
        ),
        _cmd(
            "scene.regenerate_view",
            title="重做场景单视角",
            description="生成候选场景视角，通过单图与整包 QA 后原子替换当前视角",
            input_model=I.SceneViewRegenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_scene_view_and_may_replace_ready_view",
            handler=h_scene.regenerate_view,
            rest_routes=(
                "POST /api/projects/{project_id}/scenes/{scene_name}/refs/{scene_reference_id}/views/{view_role}/regenerate",
            ),
            tags=("scene", "multiview"),
        ),
        _cmd(
            "scene.adopt_candidate",
            title="采纳场景候选图",
            description="将已通过新版硬门禁的场景候选图采纳为主图；明确硬失败不可绕过",
            input_model=I.SceneAdoptCandidateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="adopts_scene_reference_candidate",
            handler=h_scene.adopt_candidate,
            rest_routes=(
                "POST /api/projects/{project_id}/scenes/{scene_name}/candidates/{artifact_id}/adopt",
            ),
            tags=("scene",),
        ),
        _cmd(
            "scene.review_candidate",
            title="重验场景候选 QA",
            description="对已落盘场景候选执行最新硬门禁 QA；不重新生图、不切换当前资产",
            input_model=I.SceneAdoptCandidateInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.OPTIONAL,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="appends_scene_candidate_qa_evidence",
            handler=h_scene.review_candidate,
            rest_routes=(
                "POST /api/projects/{project_id}/scenes/{scene_name}/candidates/{artifact_id}/review",
            ),
            tags=("scene", "qa"),
        ),
        # —— 分集 / 剧本 / 分镜 ——
        _cmd(
            "episode.plan",
            title="分集规划",
            description="创建或替换项目分集；replace_existing 会清空剧集链",
            input_model=I.EpisodePlanInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="creates_or_replaces_episodes",
            handler=h_episode.plan,
            rest_routes=("POST /api/projects/{project_id}/plan",),
            tags=("episode",),
        ),
        _cmd(
            "screenplay.generate",
            title="生成可交付剧本",
            description="人物解析、蓝图、全局包络与场次分片合并后建立完整 Baseline，再校验发布",
            input_model=I.ScreenplayGenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="creates_run_may_clear_downstream_on_publish",
            handler=h_screenplay.generate,
            rest_routes=("POST /api/episodes/{episode_id}/screenplay",),
            supports_cancel=True,
            tags=("screenplay", "production"),
        ),
        _cmd(
            "screenplay.repair_draft",
            title="送修人工剧本（生成工作文档）",
            description="把页面提交的人工剧本送入独立 Repair 环节，仅修复 JSON/Schema/上下文绑定等结构问题并产出服务端工作文档（working Artifact）；质量问题不触发修复。与页面自动保存的会话草稿（screenplay_drafts）无关，也不直接改写已发布剧本",
            input_model=I.ScreenplayRepairDraftInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="creates_working_revision",
            handler=h_screenplay.repair_draft,
            rest_routes=("POST /api/episodes/{episode_id}/screenplay/repair-draft",),
            supports_cancel=True,
            tags=("screenplay", "production"),
        ),
        _cmd(
            "screenplay.delete",
            title="删除当前剧本",
            description="删除本集已发布剧本并清空其工作文档指针与分镜、媒体、交付等下游指针；保留历史证据，不影响页面会话草稿记录（screenplay_drafts）",
            input_model=I.ScreenplayDeleteInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_screenplay_and_downstream_products",
            handler=h_screenplay.delete,
            rest_routes=("DELETE /api/episodes/{episode_id}/screenplay",),
            tags=("screenplay", "destructive"),
        ),
        _cmd(
            "screenplay.resume",
            title="继续剧本流程",
            description="恢复未完成的首版场次分片，或从完整 working Artifact 继续校验与原子发布",
            input_model=I.ScreenplayResumeInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-text"},
            side_effect="resumes_working_revision_finalization",
            handler=h_screenplay.resume,
            rest_routes=("POST /api/episodes/{episode_id}/screenplay/resume",),
            supports_cancel=True,
            tags=("screenplay", "production", "resume"),
        ),
        _cmd(
            "screenplay.patch",
            title="剧本局部 Patch",
            description="按 Issue 对工作 Artifact 做字段/节点级修补，禁止根替换",
            input_model=I.ScreenplayPatchInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="patches_working_artifact",
            handler=h_screenplay.patch,
            rest_routes=(),
            tags=("screenplay", "production", "repair"),
        ),
        _cmd(
            "screenplay.generate_batch",
            title="批量生成剧本",
            description="批量启动无有效 revision 的剧集；warning/repairing 续跑修复而非 fresh 重生",
            input_model=I.SelectorInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="creates_batch_runs",
            handler=h_screenplay.generate_batch,
            rest_routes=("POST /api/projects/{project_id}/screenplay-all",),
            supports_cancel=True,
            tags=("screenplay",),
        ),
        _cmd(
            "screenplay.cancel",
            title="取消剧本生成",
            description="取消单集或批量剧本任务",
            input_model=I.ScreenplayCancelInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-text"},
            side_effect="cancels_run",
            handler=h_screenplay.cancel,
            rest_routes=(
                "POST /api/episodes/{episode_id}/screenplay/cancel",
                "POST /api/projects/{project_id}/screenplay-all/cancel",
            ),
            tags=("screenplay",),
        ),
        _cmd(
            "screenplay.update",
            title="保存剧本",
            description="结构化保存剧本；下游失效时需确认",
            input_model=I.ScreenplayUpdateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_screenplay_may_invalidate_downstream",
            handler=h_screenplay.update,
            rest_routes=("PUT /api/episodes/{episode_id}/screenplay",),
            tags=("screenplay",),
        ),
        _cmd(
            "storyboard.generate",
            title="开始或继续分镜任务",
            description="无分镜时开始任务；已有镜头或检查点时只允许继续任务",
            input_model=I.StoryboardGenerateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="creates_run_local_repair",
            handler=h_storyboard.generate,
            rest_routes=("POST /api/episodes/{episode_id}/storyboard",),
            supports_cancel=True,
            tags=("storyboard", "production"),
        ),
        _cmd(
            "storyboard.generate_batch",
            title="批量生成分镜",
            description="批量启动待办分镜",
            input_model=I.SelectorInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-text"},
            side_effect="creates_batch_runs",
            handler=h_storyboard.generate_batch,
            rest_routes=("POST /api/projects/{project_id}/storyboard-all",),
            tags=("storyboard",),
        ),
        _cmd(
            "storyboard.cancel",
            title="暂停分镜",
            description="立即暂停分镜生成并保留工作镜头与安全检查点",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-text"},
            side_effect="cancels_run",
            handler=h_storyboard.cancel,
            rest_routes=("POST /api/episodes/{episode_id}/storyboard/cancel",),
            tags=("storyboard",),
        ),
        _cmd(
            "shot.update",
            title="编辑镜头",
            description="结构化 Patch 更新镜头字段；保存前展示失效媒体数",
            input_model=I.ShotUpdateInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="updates_shot_may_invalidate_media",
            handler=h_storyboard.shot_update,
            rest_routes=("PUT /api/shots/{shot_id}",),
            tags=("storyboard", "shot"),
        ),
        _cmd(
            "storyboard.confirm",
            title="确认分镜",
            description="人工门禁：确认分镜并进入付费视频阶段",
            input_model=I.StoryboardConfirmInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            # confirm-preview already signs a one-time, state-bound approval
            # that the handler consumes. A second Command Bus approval leaves
            # the page stuck at HTTP 202 after the user has approved the modal.
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="human_gate_unlocks_paid_video",
            handler=h_storyboard.confirm,
            rest_routes=("POST /api/episodes/{episode_id}/confirm",),
            tags=("storyboard", "gate"),
        ),
        # —— 视频 / 参考图 ——
        _cmd(
            "video.generate_episode",
            title="全片生成视频",
            description="批量生成整集待办镜头视频",
            input_model=I.VideoGenerateEpisodeInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_batch",
            handler=h_video.generate_episode,
            rest_routes=(
                "POST /api/episodes/{episode_id}/generate",
                "POST /api/episodes/{episode_id}/video-generation-plan/{plan_id}/execute",
            ),
            tags=("video",),
        ),
        _cmd(
            "video.complete_episode",
            title="补齐全片视频",
            description="集级 Supervisor：持续生成与修复，直到每个分镜都有可用视频",
            input_model=I.VideoCompleteEpisodeInput,
            risk=RiskLevel.R2_MATERIAL,
            # 人工门取消（决策③，docs/TRANSFORM_FREEZE_PLAN.md）：这是内容质量
            # 确认门（"确认分镜后再解锁付费视频"的下一步），不是清库/删数据类
            # 破坏性操作，命令总线两阶段审批对它自动放行。破坏性操作
            # （project.delete / video.clear_* / delivery.review）保持不变。
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_completion_run",
            handler=h_video.complete_episode,
            rest_routes=("POST /api/episodes/{episode_id}/video-completion",),
            tags=("video", "supervisor"),
        ),
        _cmd(
            "video.complete_project",
            title="跨集补齐视频",
            description="项目级全局预算编排：按集顺序启动补齐 Supervisor",
            input_model=I.VideoCompleteProjectInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_project_video_completion",
            handler=h_video.complete_project,
            rest_routes=("POST /api/projects/{project_id}/video-completion",),
            tags=("video", "supervisor"),
        ),
        _cmd(
            "video.generate_shot",
            title="生成单镜视频",
            description="单镜生成，支持 prompt 覆盖、按质检问题修复、原词重抽",
            input_model=I.VideoGenerateShotInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_job",
            handler=h_video.generate_shot,
            rest_routes=("POST /api/shots/{shot_id}/generate",),
            tags=("video",),
        ),
        _cmd(
            "video.stop_shot",
            title="停止单镜视频",
            description="停止单镜活动任务；provider 侧可能仍继续",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="cancels_video_jobs",
            handler=h_video.stop_shot,
            rest_routes=("POST /api/shots/{shot_id}/video/stop",),
            tags=("video",),
        ),
        _cmd(
            "video.stop_episode",
            title="暂停整集视频任务",
            description="可恢复地暂停整集全部活动视频任务",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="pauses_episode_video_jobs",
            handler=h_video.stop_episode,
            rest_routes=("POST /api/episodes/{episode_id}/video/stop",),
            tags=("video",),
        ),
        _cmd(
            "video.adopt_version",
            title="采用视频版本",
            description="人工决策采用某版本，必须记录理由",
            input_model=I.VideoAdoptVersionInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="adopts_version_human_decision",
            handler=h_video.adopt_version,
            rest_routes=("POST /api/shots/{shot_id}/adopt",),
            tags=("video", "gate"),
        ),
        _cmd(
            "video.cancel_adoption",
            title="取消采纳视频",
            description="保留真实模型视频候选，只取消本镜采纳关系；成片禁止使用图片或静音片段代替",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="clears_shot_adoption_and_invalidates_final",
            handler=h_video.cancel_adoption,
            rest_routes=("POST /api/shots/{shot_id}/adoption/cancel",),
            tags=("video", "gate"),
        ),
        _cmd(
            "video.clear_episode",
            title="清空整集媒体",
            description="清空本集媒体产物与模型分析",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_episode_media",
            handler=h_video.clear_episode,
            rest_routes=("POST /api/episodes/{episode_id}/clear-artifacts",),
            tags=("video",),
        ),
        _cmd(
            "video.clear_shot",
            title="清空单镜媒体",
            description="清空单镜媒体产物与模型分析",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_shot_media",
            handler=h_video.clear_shot,
            rest_routes=("POST /api/shots/{shot_id}/clear-artifacts",),
            tags=("video",),
        ),
        _cmd(
            "video.clear_episode_videos",
            title="清空整集视频",
            description="只清空本集视频，保留各镜参考图",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_episode_videos",
            handler=h_video.clear_episode_videos,
            rest_routes=("POST /api/episodes/{episode_id}/videos/clear",),
            tags=("video",),
        ),
        _cmd(
            "video.clear_shot_references",
            title="清空单镜参考图",
            description="只清空本镜参考图，保留视频",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_shot_reference_images",
            handler=h_video.clear_shot_references,
            rest_routes=("POST /api/shots/{shot_id}/references/clear",),
            tags=("video", "reference"),
        ),
        _cmd(
            "video.clear_shot_videos",
            title="清空单镜视频",
            description="只清空本镜视频，保留参考图",
            input_model=I.ShotScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_shot_videos",
            handler=h_video.clear_shot_videos,
            rest_routes=("POST /api/shots/{shot_id}/videos/clear",),
            tags=("video",),
        ),
        _cmd(
            "video.delete_version",
            title="删除视频版本",
            description="删除视频版本；已采用版本禁止直接删",
            input_model=I.VersionScopedInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="deletes_version",
            handler=h_video.delete_version,
            rest_routes=("DELETE /api/versions/{version_id}",),
            tags=("video",),
        ),
        _cmd(
            "video.resume_episode",
            title="恢复集视频任务",
            description="重试预算/外部暂停的视频任务",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="resumes_video_jobs",
            handler=h_video.resume_episode,
            rest_routes=("POST /api/episodes/{episode_id}/resume",),
            tags=("video",),
        ),
        _cmd(
            "video.repair_stale_assets",
            title="修复陈旧镜头资产",
            description="依据当前人物与场景视角版本，为陈旧镜头提交新视频版本",
            input_model=I.VideoRepairStaleAssetsInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:generation-media"},
            side_effect="creates_paid_video_jobs_for_stale_shots",
            handler=h_video.repair_stale_assets,
            rest_routes=("POST /api/episodes/{episode_id}/repair-stale-assets",),
            tags=("video", "stale-assets"),
        ),
        _cmd(
            "reference.review",
            title="参考图废弃/恢复",
            description="废弃或恢复参考图；QA 淘汰恢复需理由",
            input_model=I.ReferenceReviewInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:project-write"},
            side_effect="mutates_reference_override",
            handler=h_video.reference_review,
            rest_routes=(
                "DELETE /api/versions/{version_id}/reference-images/{ref_id}",
                "POST /api/versions/{version_id}/reference-images/{ref_id}/restore",
            ),
            tags=("reference",),
        ),
        # —— 交付 ——
        _cmd(
            "delivery.concatenate",
            title="拼接成片",
            description="拼接已采用镜头为成片",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:delivery"},
            side_effect="creates_concat_job",
            handler=h_delivery.concatenate,
            rest_routes=("POST /api/episodes/{episode_id}/concatenate",),
            tags=("delivery",),
        ),
        _cmd(
            "delivery.check",
            title="检查交付就绪",
            description="重新计算 Delivery Readiness（只读计算）",
            input_model=I.EpisodeScopedInput,
            risk=RiskLevel.R0_READ,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.NONE,
            scopes={"manju:read", "manju:delivery"},
            side_effect="none_read_compute",
            handler=h_delivery.check,
            rest_routes=(),  # GET readiness 走 Resource；此 Tool 供 Agent 主动触发重算
            mcp_exposed=True,
            tags=("delivery",),
        ),
        _cmd(
            "delivery.create_package",
            title="生成交付候选",
            description="在 readiness 通过后创建待审交付包",
            input_model=I.DeliveryCreatePackageInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:delivery"},
            side_effect="creates_delivery_package",
            handler=h_delivery.create_package,
            rest_routes=("POST /api/episodes/{episode_id}/delivery/package",),
            tags=("delivery",),
        ),
        _cmd(
            "delivery.review",
            title="审批交付包",
            description="批准 / 带风险批准 / 拒绝；最高业务门禁",
            input_model=I.DeliveryReviewInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:delivery"},
            side_effect="human_delivery_gate",
            handler=h_delivery.review,
            rest_routes=("POST /api/episodes/{episode_id}/delivery/approve",),
            tags=("delivery", "gate"),
        ),
        _cmd(
            "delivery.submit_feedback",
            title="提交客户反馈",
            description="记录客户反馈并可发起修订 Run",
            input_model=I.DeliveryFeedbackInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:delivery"},
            side_effect="creates_revision_run",
            handler=h_delivery.submit_feedback,
            rest_routes=("POST /api/episodes/{episode_id}/customer-feedback",),
            tags=("delivery",),
        ),
        # —— Run / Job ——
        _cmd(
            "run.control",
            title="控制 Workflow Run",
            description="cancel / resume / retry / pause / handoff 统一入口",
            input_model=I.RunControlInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.WHEN_IMPACT,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:project-write"},
            side_effect="mutates_run_state",
            handler=h_run.control,
            rest_routes=(
                "POST /api/runs/{run_id}/cancel",
                "POST /api/runs/{run_id}/resume",
                "POST /api/runs/{run_id}/retry",
                "POST /api/runs/{run_id}/pause",
                "POST /api/runs/{run_id}/handoff",
            ),
            tags=("run",),
        ),
        _cmd(
            "job.cancel",
            title="取消媒体 Job",
            description="取消单个媒体任务",
            input_model=I.JobCancelInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.NEVER,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:generation-media"},
            side_effect="cancels_media_job",
            handler=h_run.job_cancel,
            rest_routes=("POST /api/jobs/{job_id}/cancel",),
            tags=("job",),
        ),
        # —— 系统（默认不对外 MCP） ——
        _cmd(
            "system.update_settings",
            title="更新运行设置",
            description="白名单字段更新；禁止 Agent 自动调高预算/并发",
            input_model=I.SystemUpdateSettingsInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="updates_settings",
            handler=h_system.update_settings,
            rest_routes=("PUT /api/settings",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.model_create",
            title="添加模型",
            description="加入自定义模型元数据（不含密钥明文）",
            input_model=I.SystemModelCreateInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="creates_model_metadata",
            handler=h_system.model_create,
            rest_routes=("POST /api/models",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.model_update",
            title="更新模型",
            description="更新自定义模型元数据",
            input_model=I.SystemModelUpdateInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="updates_model_metadata",
            handler=h_system.model_update,
            rest_routes=("PUT /api/models/{model_id}",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.model_delete",
            title="删除模型",
            description="删除自定义模型",
            input_model=I.SystemModelDeleteInput,
            risk=RiskLevel.R3_DESTRUCTIVE,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="deletes_model_metadata",
            handler=h_system.model_delete,
            rest_routes=("DELETE /api/models/{model_id}",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.model_test",
            title="测试模型连接",
            description="测试模型连通性；结果必须脱敏",
            input_model=I.SystemModelTestInput,
            risk=RiskLevel.R1_REVERSIBLE,
            confirmation=ConfirmationPolicy.OPTIONAL,
            idempotency=IdempotencyPolicy.RECOMMENDED,
            scopes={"manju:admin"},
            side_effect="external_connectivity_probe",
            handler=h_system.model_test,
            rest_routes=("POST /api/models/test", "POST /api/models/{model_id}/test"),
            mcp_exposed=True,
            admin_only=False,
            tags=("system",),
        ),
        _cmd(
            "system.set_engine",
            title="切换 Harness Engine",
            description="按项目启用/关闭 Workflow Engine",
            input_model=I.SystemEngineInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="toggles_engine",
            handler=h_system.set_engine,
            rest_routes=("PUT /api/projects/{project_id}/engine",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
        _cmd(
            "system.mkdir",
            title="在已授权目录下建子目录",
            description="仅允许在用户已授权的 directory_grant 下创建子目录",
            input_model=I.SystemMkdirInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="creates_directory_under_grant",
            handler=h_system.mkdir,
            rest_routes=("POST /api/system/mkdir",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system", "filesystem"),
        ),
        _cmd(
            "system.run_benchmark",
            title="运行 Benchmark",
            description="运行并记录双轨基准",
            input_model=I.BenchmarkRunInput,
            risk=RiskLevel.R2_MATERIAL,
            confirmation=ConfirmationPolicy.ALWAYS,
            idempotency=IdempotencyPolicy.REQUIRED,
            scopes={"manju:admin"},
            side_effect="creates_benchmark_run",
            handler=h_system.run_benchmark,
            rest_routes=("POST /api/benchmarks",),
            mcp_exposed=False,
            admin_only=True,
            tags=("system",),
        ),
    ]
    for spec in commands:
        registry.register_command(spec)


def _register_exemptions(registry) -> None:
    """协议/编排/运维入口本身不是领域命令：登记豁免原因，满足覆盖门禁。"""
    registry.exempt_rest(
        "POST /api/system/mcp-tokens",
        "MCP token 生命周期管理是运维端点；Agent/外部 MCP 客户端不能自我签发或升级授权范围",
    )
    registry.exempt_rest(
        "DELETE /api/system/mcp-tokens/{token_id}",
        "同上：token 撤销只能由本机操作者通过监制房页面执行，不进入 Agent/MCP 能力面",
    )
    registry.exempt_rest(
        "POST /api/system/directory-grants",
        "本机人工授权可浏览/建目录根；仅本机会话可写，不向 Agent/MCP 开放",
    )
    registry.exempt_rest(
        "POST /api/auth/login",
        "账号登录是鉴权入口本身：签发会话先于任何 workspace/scope 判定，不经 Command Bus",
    )
    registry.exempt_rest(
        "POST /api/auth/logout",
        "只撤销调用者自己当前的会话，不改变任何制作领域状态",
    )
    registry.exempt_rest(
        "POST /api/auth/change-password",
        "账号自助改密：仅影响操作者自身口令与会话，不是领域命令，不向 Agent/MCP 开放",
    )
    registry.exempt_rest(
        "POST /api/system/users",
        "开户是运维身份管理，不是制作领域命令；仅系统管理员可调用，不向 Agent/MCP 开放",
    )
    registry.exempt_rest(
        "PUT /api/system/users/{user_id}",
        "编辑账号（改密/启停/管理员标记）同上，仅系统管理员可调用",
    )
    registry.exempt_rest(
        "POST /api/system/workspaces",
        "建团队是运维身份管理，不是制作领域命令；仅系统管理员可调用",
    )
    registry.exempt_rest(
        "PUT /api/system/workspaces/{workspace_id}",
        "改团队名/停用启用属运维身份管理，不是制作领域命令；仅系统管理员可调用",
    )
    registry.exempt_rest(
        "PUT /api/system/workspaces/{workspace_id}/members/{user_id}",
        "团队成员角色分配是运维身份管理，仅系统管理员可调用",
    )
    registry.exempt_rest(
        "DELETE /api/system/workspaces/{workspace_id}/members/{user_id}",
        "移出团队成员是运维身份管理，仅系统管理员可调用",
    )
    registry.exempt_rest(
        "POST /api/agent/conversations",
        "Agent 会话编排入口，不直接改变制作领域状态",
    )
    registry.exempt_rest(
        "POST /api/agent/conversations/{conversation_id}/messages",
        "Agent Turn 编排入口；写操作仍经 Command Bus",
    )
    registry.exempt_rest(
        "POST /api/agent/turns/{turn_id}/cancel",
        "仅取消 Agent Turn；底层 Run 需显式 cancel_run 才走 run.control",
    )
    registry.exempt_rest(
        "POST /api/agent/tool-calls/{tool_call_id}/approve",
        "批准卡协议入口，执行仍走已注册 Domain Tool",
    )
    registry.exempt_rest(
        "POST /api/agent/tool-calls/{tool_call_id}/reject",
        "拒绝卡协议入口，不执行领域命令",
    )
    registry.exempt_rest(
        "POST /api/episodes/{episode_id}/video-completion/reset",
        "生成台死锁解锁：强制停止补齐 Supervisor 并复位面板；不创建新付费任务",
    )
    registry.exempt_rest(
        "POST /api/episodes/{episode_id}/video-completion/repair",
        "遗留事故收口端点：必须先 dry-run 且由本机操作者 confirm=true；只停止任务和采用既有候选，不创建付费任务",
    )
    registry.exempt_rest(
        "POST /api/episodes/{episode_id}/migrate-shot-ids",
        "VAL-422 历史 ID 空间迁移：把误写入 story_event_id 的 S* 迁到 spine_beat_ids；只修合同字段，不启动付费任务",
    )
    registry.exempt_rest(
        "POST /api/shots/{shot_id}/resolve-spoken-conflict",
        "口播合同冲突人工消解：在 dialogues / audio_timeline 间选基准同步；页面直达，不进入 Agent/MCP 能力面",
    )
    registry.exempt_rest(
        "POST /api/projects/{project_id}/bible/impact-preview",
        "人物谱定稿前只读影响预检：不写库、不失效下游；正式定稿仍走 bible.update",
    )
    registry.exempt_rest(
        "POST /api/projects/{project_id}/refs/precheck",
        "定妆照/单视角付费只读预检：返回报价与范围；正式生成仍走 portrait.generate / portrait.regenerate_view",
    )
    registry.exempt_rest(
        "POST /api/projects/{project_id}/bible/generate-precheck",
        "首次生成人物谱+定妆只读费用预估；正式启动仍走 bible.generate",
    )
    registry.exempt_rest(
        "GET /api/projects/{project_id}/refs/gaps",
        "定妆缺口只读扫描",
    )
    registry.exempt_rest(
        "GET /api/projects/{project_id}/refs/progress",
        "定妆进度只读汇总",
    )
    registry.exempt_rest(
        "POST /api/projects/{project_id}/bible/draft",
        "人物谱草稿保存：不定稿、不失效下游",
    )
    registry.exempt_rest(
        "GET /api/projects/{project_id}/bible/draft",
        "读取人物谱草稿",
    )
    registry.exempt_rest(
        "GET /api/projects/{project_id}/auto-changes",
        "自动变更待审队列只读",
    )
    registry.exempt_rest(
        "POST /api/projects/{project_id}/auto-changes/{change_id}/decide",
        "自动变更批准/拒绝/回滚；页面人工决策入口",
    )
    registry.exempt_rest(
        "PUT /api/projects/{project_id}/characters/{character_name}",
        "角色级人物谱保存：局部替换角色对象，内部复用人物谱版本与影响预检",
    )
    registry.exempt_rest(
        "GET /api/projects/{project_id}/characters/{character_name}/portrait-candidates",
        "角色定妆候选只读列表",
    )
    registry.exempt_rest(
        "POST /api/projects/{project_id}/characters/{character_name}/portraits/{portrait_id}/adopt",
        "人物定妆候选人工采纳；页面评审入口，写入 gate/change 决策",
    )
    registry.exempt_rest(
        "POST /api/projects/{project_id}/characters/{character_name}/portraits/{portrait_id}/rollback",
        "人物定妆候选人工回滚；页面评审入口，复用采纳切换逻辑",
    )
    for route, reason in {
        "PUT /api/episodes/{episode_id}/screenplay/draft": "剧本台会话草稿写入（screenplay_drafts）；仅页面自动保存的未发布编辑内容，不发布、不触发生成、不进入下游；与 Repair 工作文档、已发布剧本无关",
        "DELETE /api/episodes/{episode_id}/screenplay/draft": "剧本台会话草稿清理；只删除 screenplay_drafts 中该分集的会话草稿记录，不影响 Repair 工作文档（working_screenplay_artifact_id）与已发布剧本（screenplay_json）",
        "DELETE /api/shots/{shot_id}/drafts/{draft_id}": "分镜编辑会话草稿清理；不改变已发布产物",
        "POST /api/episodes/{episode_id}/confirm-preview": "分集确认前只读影响预览；正式确认仍走已登记命令",
        "POST /api/episodes/{episode_id}/screenplay/preflight": "剧本生成前只读输入范围与人物资产影响预检",
        "POST /api/episodes/{episode_id}/screenplay/impact-preview": "剧本发布前只读影响预览；不写库、不建任务，正式发布仍走 screenplay.update",
        "POST /api/episodes/{episode_id}/storyboard/preflight": "分镜生成前只读预检与短时凭证签发",
        "POST /api/episodes/{episode_id}/storyboard/clear-preview": "整集分镜清空前的影响预览与短时凭证签发；不删除制作数据",
        "POST /api/episodes/{episode_id}/storyboard/clear": "分镜台本机人工清空入口；必须消费当前影响预览凭证，不向 Agent/MCP 开放",
        "POST /api/episodes/{episode_id}/video-model": "分镜台人工切换本集绑定视频模型入口；已有生成产物时必须显式 confirm_clear_prompts 二次确认，且该清空分支要求 manju:project-write（与 video.clear_episode_videos 同档，review/readonly 会被 403 挡下）；无产物的普通切换不受此限，不向 Agent/MCP 开放",
        "POST /api/episodes/{episode_id}/provider-tasks/reconcile": "分镜台清空/切换视频模型撞上 409 PROVIDER_TASKS_NOT_TERMINAL 的人工恢复入口；只做两件事——核对仍疑似在途的供应商任务真实终态（供应商自己确认成功/失败才结算），以及关闭本地证据已证明「从未提交给供应商、所属镜头已有其他成功版本」的孤儿任务；不下载或采用任何结果、不提交新任务、不放宽闸门，要求 manju:project-write（与 video-model 清空分支同档），不向 Agent/MCP 开放",
        "PUT /api/projects/{project_id}/text-models": "世界书/映射台/分镜台分环节专属文本模型的人工切换入口（bible_text_provider/script_text_provider/board_text_provider）；项目级设置，与分镜台「视频模型」的分集级强绑定是两回事——这里只影响之后新发起的该环节生成调用选哪个 provider，不清空已有产出、不需要二次确认。全端点收在 manju:project-write（与 video-model 的清空分支同档，review/readonly 会被 403 挡下），不向 Agent/MCP 开放",
        "POST /api/episodes/{episode_id}/storyboard/structure-preview": "分镜结构变更前只读预览",
        "POST /api/episodes/{episode_id}/storyboard/structure": "分镜台人工结构编辑入口；必须消费页面预览凭证",
        "POST /api/gates/{artifact_id}/decision": "证据门禁的人工决策入口；禁止 Agent 自行代替人类批准",
        "POST /api/projects/{project_id}/observability/gates/{artifact_id}/decision": "项目范围观测台的证据门禁代理；校验项目归属后转发到既有人工决策入口，仍禁止 Agent 代替用户批准",
        "POST /api/projects/{project_id}/observability/jobs/{job_id}/{action}": "项目范围观测台的任务动作代理；校验项目归属后仅转发到已登记的 Run 控制、媒体 Job 取消或本机管理员重试入口",
        "POST /api/projects/{project_id}/observability/runs/{run_id}/{action}": "项目范围观测台的 Run 动作代理；校验项目归属后转发到已登记的 run.control 路由并沿用其批准策略",
        "POST /api/projects/{project_id}/scene-bible/precheck": "场景清单生成前只读付费预检",
        "POST /api/projects/{project_id}/scene-bible/preview": "场景清单与付费范围只读预览",
        "POST /api/projects/{project_id}/scene-refs/precheck": "场景图付费生成前只读预检",
        "POST /api/projects/{project_id}/scene-reviews": "历史场景包本机管理复验；不启动付费出图",
        "POST /api/projects/{project_id}/scene-reviews/{batch_id}/cancel": "取消本机场景历史复验任务",
        "POST /api/projects/{project_id}/scene-reviews/{batch_id}/items/{item_id}/disposition": "场景历史复验的人工处置记录；不删除历史资产且不向 Agent/MCP 开放",
        "POST /api/projects/{project_id}/scenes/{scene_name}/refs/{scene_reference_id}/views/{view_role}/regenerate/cancel": "页面定向取消单场景视角任务，不创建新付费作业",
        "POST /api/projects/{project_id}/scenes/{scene_name}/refs/{scene_reference_id}/rollback": "场景库历史版本人工回滚；页面评审入口，不向 Agent/MCP 开放",
        "PUT /api/projects/{project_id}/scenes/{scene_name}": "场景库人工元数据修订；页面编辑入口，不自动触发付费出图",
        "POST /api/shots/{shot_id}/edit-session": "分镜编辑租约签发；不改变分镜内容",
        "POST /api/shots/{shot_id}/impact-preview": "分镜修订前只读影响预览",
        "POST /api/shots/{shot_id}/spoken-conflict-preview": "分镜口播冲突处理前只读预览",
        "POST /api/system/jobs/{job_id}/retry": "监制房运维重试入口；只限本机管理员",
        "POST /api/system/monitor/events": "前端监控事件采集入口；只记录遥测，不执行领域动作",
        "POST /api/versions/{version_id}/archive": "生成台人工归档操作；不删除媒体，不向 Agent/MCP 开放",
        "DELETE /api/versions/{version_id}/archive": "生成台人工取消归档操作；不向 Agent/MCP 开放",
        "POST /api/episodes/{episode_id}/video-generation-plan": "整集 AI 模式计划阶段；只生成并校验版本化计划，不创建视频供应商付费任务",
        "POST /api/episodes/{episode_id}/video-generation-plan/validate": "视频模式计划确定性只读复核；不创建或执行媒体任务",
        "POST /api/episodes/{episode_id}/video-generation-plan/reconcile": "采用版本变更后的工具输入绑定与 stale 标记；不创建新付费任务",
        "POST /api/episodes/{episode_id}/video-generation-plan/override": "生成台运营调试的人工覆盖入口；必须记录理由且生成新计划 revision，不向 Agent/MCP 开放",
        "POST /api/video-capabilities/{provider}/{model:path}/probe": "供应商能力真实付费探针；仅本机操作者显式 confirm 后执行，不向 Agent/MCP 开放",
        "POST /api/provider-media-publications": "内部媒体发布协议入口；仅发布项目自有媒体并执行 URL/哈希校验，不作为 Agent 领域工具",
    }.items():
        registry.exempt_rest(route, reason)
    registry.exempt_rest(
        "POST /mcp",
        "MCP JSON-RPC 传输端点；具体 tools/call 映射到 Capability Registry",
    )
